### ISSUE TITLE
Svg icons won't show in grafana/ui library react components

### ISSUE THREAD

**Issue by AlexanderBrese** [devilwjp/veaury#10]
Hello there 
I use vue 3, vite, grafana/ui, veaury

first of thank you very much for this library it surely helps a lot.
I try to use it with grafana/ui which is made up of react components internally. When I try to use a Button for example and pass an icon string prop it internally processes the svg with react-inline-svg and then uses a dom parser to get the node of the parsed svg text. For some reason it doesn't work for me. I do get the following error:
![grafik](https://user-images.githubusercontent.com/24847484/169668915-be0cd3b1-a195-42a0-965b-81321e38c31a.png)
Which is located here:
![grafik](https://user-images.githubusercontent.com/24847484/169668939-5ff81b3f-31d8-469a-96f2-d5dccb48e97e.png)
And used first here:
![grafik](https://user-images.githubusercontent.com/24847484/169668961-0050fd7f-b86d-4909-a99a-d8cc250845f5.png)
Inside grafana_ui.js
One of the components in question:
![grafik](https://user-images.githubusercontent.com/24847484/169668988-a716beff-8392-46ad-9b9e-9d26b01126c1.png)
The processed svg is correct:
data:image/svg+xml,%3csvg id='Layer_1' data-name='Layer 1' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'%3e%3cpath d='M12%2c6a.99974.99974%2c0%2c0%2c0-1%2c1v4H9a1%2c1%2c0%2c0%2c0%2c0%2c2h3a.99974.99974%2c0%2c0%2c0%2c1-1V7A.99974.99974%2c0%2c0%2c0%2c12%2c6Zm0-4A10%2c10%2c0%2c1%2c0%2c22%2c12%2c10.01146%2c10.01146%2c0%2c0%2c0%2c12%2c2Zm0%2c18a8%2c8%2c0%2c1%2c1%2c8-8A8.00917%2c8.00917%2c0%2c0%2c1%2c12%2c20Z'/%3e%3c/svg%3e

It seemed to work in vuera with vue 2.

**Comment by devilwjp** [comment]
@AlexanderBrese 
This doesn't seem to be a veaury problem. When I create a new react project, import @grafana/ui, and use IconButton, this error occurs

And I also found this [issue](https://github.com/grafana/grafana/issues/37052), which is very similar to this problem

**Comment by devilwjp** [comment]
@AlexanderBrese 
I tried using @grafana/ui@canary and everything works fine!

**Comment by AlexanderBrese** [comment]
@devilwjp Thank you Sir. It works now.
Another thing I've noticed is that I do get the following error when I run pnpm build now:
```
error during build:
Error: 'default' is not exported by node_modules/.pnpm/react@17.0.2/node_modules/react/index.js, imported by node_modules/.pnpm/veaury@1.0.5/node_modules/veaury/dist/veaury.esm.js
    at error (/home/alex/WebstormProjects/frontend/node_modules/.pnpm/rollup@2.74.1/node_modules/rollup/dist/shared/rollup.js:198:30)
    at Module.error (/home/alex/WebstormProjects/frontend/node_modules/.pnpm/rollup@2.74.1/node_modules/rollup/dist/shared/rollup.js:12555:16)
    at Module.traceVariable (/home/alex/WebstormProjects/frontend/node_modules/.pnpm/rollup@2.74.1/node_modules/rollup/dist/shared/rollup.js:12914:29)
    at ModuleScope.findVariable (/home/alex/WebstormProjects/frontend/node_modules/.pnpm/rollup@2.74.1/node_modules/rollup/dist/shared/rollup.js:11543:39)
    at FunctionScope.findVariable (/home/alex/WebstormProjects/frontend/node_modules/.pnpm/rollup@2.74.1/node_modules/rollup/dist/shared/rollup.js:6517:38)
    at ChildScope.findVariable (/home/alex/WebstormProjects/frontend/node_modules/.pnpm/rollup@2.74.1/node_modules/rollup/dist/shared/rollup.js:6517:38)
    at FunctionScope.findVariable (/home/alex/WebstormProjects/frontend/node_modules/.pnpm/rollup@2.74.1/node_modules/rollup/dist/shared/rollup.js:6517:38)
    at ChildScope.findVariable (/home/alex/WebstormProjects/frontend/node_modules/.pnpm/rollup@2.74.1/node_modules/rollup/dist/shared/rollup.js:6517:38)
    at MemberExpression.bind (/home/alex/WebstormProjects/frontend/node_modules/.pnpm/rollup@2.74.1/node_modules/rollup/dist/shared/rollup.js:8736:49)
    at CallExpression.bind (/home/alex/WebstormProjects/frontend/node_modules/.pnpm/rollup@2.74.1/node_modules/rollup/dist/shared/rollup.js:5361:23)
    ```

**Comment by devilwjp** [comment]
@AlexanderBrese 
The problem you mentioned above should be that vite encountered a problem when analyzing commonjs.
React is currently a pure CommonJS package that only supports the following usages:
```js
import * as React from 'react'
import { Suspense } from 'react'
```  
But in veaury, I use non-standard usage:
```js
import React from 'react'
```
This non-standard usage is that webpack, tsc and other tools have done special treatment, uniformly packaged in the form of `{ default: ... }`, and added the default field.  
I will fix this in a future version of veaury.  
So how do you fix this error now? I think you can add `defaultIsModuleExports: false` in `build.commonjsOptions` in `vite.config.js`.  
```js
// The vite.config.js you provided
// .......
export default defineConfig({
 //......
  build: {
    commonjsOptions: {
      include: [/react/, /vue3-openlayers/, /vue-grid-layout/, /timezones/],
      defaultIsModuleExports: false
    },
    // ......
  },
// .......
```
Try it again, hope that solves the problem!!!

**Comment by AlexanderBrese** [comment]
https://github.com/rollup/plugins/issues/1111

**Comment by devilwjp** [comment]
@AlexanderBrese 
This issue is not a problem to be solved by rollup, but what vite should do, try it!

**Comment by devilwjp** [comment]
But interestingly, the example project I provided doesn't build with this error

**Comment by AlexanderBrese** [comment]
Thank you very much it worked like a charm.

> But interestingly, the example project I provided doesn't build with this error
That might be because I'm using pnpm but I'm not sure though.

**Comment by devilwjp** [comment]
You can temporarily manually modify the usage of import React and reactDOM from vessel.esm.js in node_modules

**Comment by AlexanderBrese** [comment]
> You can temporarily manually modify the usage of import React and reactDOM from veaury.esm.js in node_modules

Thanks I'll try that.

Have you ever stumbled upon `Po.propTypes is undefined`? - I've seen in your example that you have proptypes as a dependency.

**Comment by devilwjp** [comment]
Many packages depend on prop-types.  
![image](https://user-images.githubusercontent.com/38802722/169705653-115d0f20-1704-4d73-a7c1-1ff20e387a2f.png)

**Comment by AlexanderBrese** [comment]
Hmm strange why do i get this error when i try to access the view with grafana/ui in it in the built version...

**Comment by devilwjp** [comment]
You can run `npm ls prop-type` to see if all `prop-type` versions are the same

**Comment by AlexanderBrese** [comment]
> You can run `npm ls prop-type` to see if all `prop-type` versions are the same

Ok thats what I thought. I'm using pnpm and with pnpm the list is empty.

**Comment by devilwjp** [comment]
Can you try adding prop-type to package.json, then delete node_modules and pnpm-lock.json, and try to reinstall

**Comment by AlexanderBrese** [comment]
I just tried that and also imported PropTypes but it didn't work.

**Comment by devilwjp** [comment]
If you directly import react components dynamically, you need to use lazyReactInVue

**Comment by AlexanderBrese** [comment]
Ok i just tried directly loading the view and the error persists.

**Comment by devilwjp** [comment]
@AlexanderBrese 
Will loading the view into the sample project I provided display fine? If it works fine, then compare the differences in the configuration of these two project

**Comment by AlexanderBrese** [comment]
Thanks I will definitely try this.
Sir I can not thank you enough for all your help.

**Comment by AlexanderBrese** [comment]
I'm not sure what the issue is the error message doesn't really help. I've tried your example and just ran npm run build and it didn't work (prop-type error). Could you maybe check it?

**Comment by devilwjp** [comment]
@AlexanderBrese 
OK, can you provide an example for me to debug? It would be better to add your example to the example project I provided.

**Comment by AlexanderBrese** [comment]
You should be able to receive the error when you run "npm run build" on the example project you gave me. I had the same issue there in build mode.

**Comment by devilwjp** [comment]
@AlexanderBrese 
Is the following error message?  
![image](https://user-images.githubusercontent.com/38802722/169796238-5cd346a2-19a3-48dd-840d-c9bc9a08e136.png)

**Comment by AlexanderBrese** [comment]
Yes I think you get the propTypes error message when you run it on firefox but I'm not sure. I got a different one on chrome.

**Comment by AlexanderBrese** [comment]
I tried setting defaultIsModuleExports: false. Didn't work.

**Comment by devilwjp** [comment]
@AlexanderBrese 
Wow!!!，I found the cause of the problem!!!
`@grafana/ui/index.production.js` require `./ReactMonacoEditor.production.js` by causing a circular dependency

![image](https://user-images.githubusercontent.com/38802722/169892348-875affcb-3c4c-458e-b459-41ba111d2f25.png)

So you need to use dynamic require, and install the latest version of @rollup/plugin-commonjs.
In the `include` of `commonjsOptions` , there is no need to add any path.
```js
commonjsOptions: {
  // '@grafana/ui' require './ReactMonacoEditor.production.js' by causing a circular dependency
  // So you need to use dynamic require
  dynamicRequireTargets : [
    'node_modules/@grafana/ui/ReactMonacoEditor.production.js' ,
  ]
}
```

**Comment by AlexanderBrese** [comment]
Sir, thank you for all you’ve done. I owe you big-time. I will try that out.
