### ISSUE TITLE
请教下大佬关于 Vue 下使用 React 组件时，属性是 JSX.Element 的问题

### ISSUE THREAD

**Issue by 6af2d826** [devilwjp/veaury#109]
官方文档是用的 React 组件: https://lexical.dev/docs/getting-started/react

![image](https://github.com/devilwjp/veaury/assets/157440465/bf7fc3df-921b-4b55-9ed1-1356cc81d518)
想转为 Vue，但只能再装上 React （Vue 与 React 共存）才能不报错，单纯用 Vue 不知道如何解决如下这个问题：
https://stackblitz.com/edit/vitejs-vite-xtv7bp?file=src%2FApp.vue,src%2Freact_app%2FEditor.jsx,package.json,src%2FEditor.vue%3AL23
![image](https://github.com/devilwjp/veaury/assets/157440465/bbe89961-0003-4e01-a2c8-a244cfedfea8)

**Comment by devilwjp** [comment]
@6af2d826 底层是react组件，veaury只是让你的vue项目可以使用react组件，并不会将react组件转换为vue组件，所以react是必须要安装的
