### ISSUE TITLE
Your react_ app is the  folder?

### ISSUE THREAD

**Issue by h7ml** [devilwjp/veaury#11]
![image](https://user-images.githubusercontent.com/55233292/171104266-521a4eb3-3375-4230-b5a4-7a769425f7e3.png)
![image](https://user-images.githubusercontent.com/55233292/171104292-bcc0bb4c-ae81-45e6-840e-1032e33fff43.png)

**Comment by devilwjp** [comment]
@h7ml 
The scope is any directory named react_app.

**Comment by h7ml** [comment]
> The scope is any directory named react_app.
> For example, 'src/pages/aaa/react_app', another example, 'src/react_app', etc.
> Don't configure react_app in alias, because `veaury/babelPreset` has already done related internal configuration.

Thank you very much
