### ISSUE TITLE
React strict mode nothing rendering

### ISSUE THREAD

**Issue by amritk** [devilwjp/veaury#112]
When react strict mode is enabled, there is nothing rendered in the component. No errors are thrown either. Is there a way to see what the error is?

```ts
const VeauryComponent = applyVueInReact(ApiClient) as JSX.ElementType
...
<VeauryComponent />
...
```

It works fine when strict mode is disabled

**Comment by devilwjp** [comment]
@amritk 
You can run the react test project(dev-project-react/src/index.js) in the veaury source code and remove the strict mode comments. It works fine.

![image](https://github.com/devilwjp/veaury/assets/38802722/9ab1d784-6c28-403d-83ba-02b8b641f675)

**Comment by devilwjp** [comment]
@amritk 
I think the type definition of VeauryComponent may be wrong. It should be a component, not elementType.

**Comment by amritk** [comment]
Hmm maybe it has something to do with my setup then. Thanks
