### ISSUE TITLE
v-for with several applyPureReactInVue components breaks reactivity

### ISSUE THREAD

**Issue by nhaustov** [devilwjp/veaury#120]
Using applyPureReactInVue sometimes causes reactivity to stop working. I have created a simple example based on dev-project-vue3 (full diff attached). Typing into inputs does not cause model to update. Same React components with applyReactInVue wrappers works.

```
    <PureBox>
      <span>v-for with PureInput wrapped in PureBox breaks. Typing into inputs do not change values.</span>
      <PureBox v-for="e in arr2" :key="e.id">
          <PureInput :value="e.value" @change="e.value = $event.target.value"/>
      </PureBox>
    </PureBox>

...
const PureBox = applyPureReactInVue(ReactBox)
const PureInput = applyPureReactInVue(ReactInput)
```

[diff.txt](https://github.com/devilwjp/veaury/files/14969958/diff.txt)

**Comment by devilwjp** [comment]
@nhaustov Thank you! This bug will be fixed recently.

**Comment by devilwjp** [comment]
@nhaustov try 2.3.17-beta.1, `npm run veaury@beta`

**Comment by nhaustov** [comment]
@devilwjp Confirmed - the fix works with the simple example as well as my more complex app. Thanks - appreciate your work! I do have few more issues to report separately.
