### ISSUE TITLE
watch does not work for children of applyPureReactInVue

### ISSUE THREAD

**Issue by nhaustov** [devilwjp/veaury#122]
We are using watch on ref to attach something to diff when it is initialized (not on mount). It works when div is a child of Vue component or simple diff but not with children of applyPureReactInVue component.
Attached is a minimized example under dev-project-vue3 (watchref). The refs are initialized 3 seconds after the component is mounted and then changed after another 3 seconds. It works for box2 and box3 but not for box1. In the console output is below - note no "box1 changed".
The problem also happens with 2.3.17-beta.1 (with fix to #120).

[diff.txt](https://github.com/devilwjp/veaury/files/15052793/diff.txt)

box1 undefined
index.vue:48 box2 undefined
index.vue:49 box3 undefined
index.vue:39 box2 changed <div>​</div>​ undefined undefined
index.vue:43 box3 changed <div>​</div>​ undefined undefined
index.vue:39 box2 changed null <div>​</div>​ undefined
index.vue:43 box3 changed null <div>​</div>​ undefined
index.vue:39 box2 changed <div>​</div>​ null undefined
index.vue:43 box3 changed <div>​</div>​ null undefined

**Comment by devilwjp** [comment]
@nhaustov try `2.3.17-beta.2`
