### ISSUE TITLE
可否提供一份在React项目中使用Vue3组件的Vite配置文件

### ISSUE THREAD

**Issue by pawover** [devilwjp/veaury#13]
在issues中只找到了Vue项目使用React组件的配置

我想尝试一下这个库，谢谢

**Comment by devilwjp** [comment]
@Handpear 
你是react的vite项目是吧？配置如下  
```js
// vite.config.js
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import vue from '@vitejs/plugin-vue'
import vueJsx from '@vitejs/plugin-vue-jsx'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react({
      babel: {
        exclude: [/\.vue$/]
      }
    }),
    vue(),
    vueJsx({
      // exclude react_app directory
      include: [/\.vue$/]
    }),
  ]
})
```

**Comment by Handpear** [comment]
@devilwjp 
感谢，在React 17 中测试成功了，但是 React 18 中会报错，但似乎不是 veaury 的问题
![image](https://user-images.githubusercontent.com/40299372/176078251-3e898123-f190-4bb2-8a5b-1baf0e158115.png)
有办法解决吗

**Comment by Handpear** [comment]
好吧，是 TS 的断言被编译进了代码里，我看看怎么修改

**Comment by Handpear** [comment]
似乎 vite 失去了对 ts 的编译能力?

**Comment by devilwjp** [comment]
@Handpear 
是vueJsx导致的，暂时先不要写vue的jsx吧
```js
// vite.config.js
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import vue from '@vitejs/plugin-vue'
import vueJsx from '@vitejs/plugin-vue-jsx'

export default defineConfig({
  plugins: [
    react(),
    vue()
  ]
})
```

**Comment by devilwjp** [comment]
> 似乎 vite 失去了对 ts 的编译能力?

@Handpear 
修改配置如下，记得安装`@vue/babel-plugin-jsx`  
```js
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [
    vue(),
    react({
      babel: {
        // 预设vuejsx插件处于关闭状态
        plugins: [['@vue/babel-plugin-jsx', false]],
        overrides: [{
          // 将vuejsx插件开启
          include: [/vue&type=script&lang.[tj]sx?$/],
          plugins: ['@vue/babel-plugin-jsx']
        }]
      }
    }),
  ]
})
```

**Comment by devilwjp** [comment]
@Handpear 
升级到2.1.1版本

```js
import { defineConfig } from 'vite'
// >= veaury@2.1.1
import veauryVitePlugins from 'veaury/vite/index'

export default defineConfig({
  plugins: [
    // 关闭 react plugin
    // react(),
    // 当type设置为react, 
    // 只有.vue文件中的jsx会被以vue jsx编译, 
    // 其他的文件中的jsx都会被以react jsx编译
    veauryVitePlugins({
      type: 'react'
    })
  ]
})
```

**Comment by Handpear** [comment]
@devilwjp 感谢，其实上一版的配置已经能用了，只不过Eslint把所有React jsx 都识别为了 Vue jsx，tsconfig文件肯定是需要两个的，设置不同的 jsx 模式，但 eslint 是需要通过 overrides 字段复写文件类型吗？

**Comment by devilwjp** [comment]
@Handpear 
我最近回复的两个配置都能用的，最后一个配置只是把前一个配置包装了一下而已  
是因为vueJsx插件会默认设置vite的esbuild的include为/\.ts/，也就是只让esbuild只处理ts文件的typescript编译，其他文件都默认走vueJsx插件使用babel的ts插件，但是比较可惜的是vueJsx的vite插件并没后设置enforce为pre，导致优先级不如react插件（因为react插件设置了enforce为true），所以正确的配置是依旧使用react插件，但是预先把@vue/babel-plugin-jsx插入到react插件的plugins里（优先级最高，但是设置为关闭），然后就通过overrides来做条件的匹配选择是否开启vue的jsx编译即可

**Comment by Candidade** [comment]
vue3引入react组件，按此库文档操作更改balel配置，运行出错，貌似没构建，有大佬知晓麻烦回复回复嘛
![企业微信截图_16602889176586(1)](https://user-images.githubusercontent.com/62602475/184823282-ebd24f2d-cddd-48fc-bb28-0b7b68f64e2f.png)
![企业微信截图_16602891301073(1)](https://user-images.githubusercontent.com/62602475/184823314-c84f0f8f-ba88-4584-92de-822d623bcb68.png)

**Comment by devilwjp** [comment]
@Candidade vue3引入react，参考一下我的文档关于webpack的部分，应该使用veaury的babel插件

**Comment by xiaobc1234** [comment]
最新版插件在vite3 vue3中使用react情况下第二种配置报下面错
![image](https://user-images.githubusercontent.com/4045741/223608958-4d49b297-0c7c-4b1e-ad21-0986dd8df6b8.png)

换用第一种方式正常，估计是包装有问题
`import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [
    vue(),
    react({
      babel: {
        // 预设vuejsx插件处于关闭状态
        plugins: [['@vue/babel-plugin-jsx', false]],
        overrides: [{
          // 将vuejsx插件开启
          include: [/vue&type=script&lang\.[tj]sx?$/],
          plugins: ['@vue/babel-plugin-jsx']
        }]
      }
    }),
  ]
})
`

**Comment by devilwjp** [comment]
@xiaobc1234 请直接使用veaury的vite插件

https://github.com/devilwjp/veaury#vite

**Comment by devilwjp** [comment]
@Fucntion 提供一个例子给我

**Comment by xiaobc1234** [comment]
> @xiaobc1234 请直接使用veaury的vite插件
> 
> https://github.com/devilwjp/veaury#vite

我一开始是这么用的，但是报上面的错，换成第一种方式就正常：

`  "veaury": "^2.3.12" `

` import { defineConfig } from 'vite';
import Unocss from 'unocss/vite';
import { resolve } from 'pathe';
import vue from '@vitejs/plugin-vue';
import AutoImport from 'unplugin-auto-import/vite';
import VueI18n from '@intlify/vite-plugin-vue-i18n';
import Components from 'unplugin-vue-components/vite';
import { AntDesignVueResolver } from 'unplugin-vue-components/resolvers';
import ViteFonts from 'vite-plugin-fonts';
import svgLoader from 'vite-svg-loader';
import veauryVitePlugins from 'veaury/vite/index.js';
import react from '@vitejs/plugin-react';

const DEV_API_HOST = 'http://localhost:7001';

// https://vitejs.dev/config/
export default defineConfig({
  base: './',
  server: {
    port: 4000,
    proxy: {
      // 配置 swg 代理地址
      '/api': {
        target: DEV_API_HOST,
        changeOrigin: true,
        secure: false,
        configure,
      },
    },
  },
  resolve: {
    alias: {
      '~theme-cn-ui-light': 'theme-cn-ui-light',
      vue: 'vue/dist/vue.esm-bundler.js',
      '/@': resolve(__dirname, './src'),
      '@src': resolve(__dirname, './src'),
      '@services': resolve(__dirname, './src/services'),
    },
  },
  plugins: [
    // veaury插件需要 关闭 vue 和 vuejsx 插件
    // vue(),
    // vueJsx(),
    veauryVitePlugins({
      type: 'vue',
    }),
    AutoImport({
      dts: 'src/auto-imports.d.ts',
      imports: ['vue', 'vue-router'],

      eslintrc: {
        enabled: true,
        filepath: './.eslintrc-auto-import.json',
        globalsPropValue: true,
      },
    }),
    // https://github.com/jpkleemans/vite-svg-loader
    svgLoader(),
    // https://github.com/antfu/vite-plugin-components
    Components({
      extensions: ['vue'],
      dts: 'src/components.d.ts',
      deep: true,
      dirs: ['src/components'],
      resolvers: [
        AntDesignVueResolver({
          importStyle: false,
        }),
      ],
    }),
    // https://github.com/stafyniaksacha/vite-plugin-fonts#readme
    ViteFonts({
      google: {
        families: ['Open Sans', 'Montserrat', 'Fira Sans'],
      },
    }),

    Unocss({
      /* options */
    }),

    // https://github.com/intlify/vite-plugin-vue-i18n
    VueI18n({
      include: [resolve(__dirname, './locales/**')],
    }),
  ],
  css: {
    preprocessorOptions: {
      less: {
        // DO NOT REMOVE THIS LINE
        javascriptEnabled: true,
        modifyVars: {
          // hack: `true; @import 'ant-design-vue/dist/antd.variable.less'`,
          // '@primary-color': '#eb2f96', // 全局主色
        },
      },
    },
  },
  optimizeDeps: {
    include: [
      'vue',
      'vue-router',
      '@vueuse/core',
      '@ant-design/icons-vue',
      'ant-design-vue/es',
      '@ant-design-vue/pro-layout',
    ],
    exclude: ['vue-demi'],
  },
});

function configure(proxy, options) {
  // 本地可直接走登录流程，无需手动设置cookie了。
  proxy.on('proxyRes', function (proxyRes, req, res) {
    console.log('proxy url: ', req.url);
    if (proxyRes.headers['set-cookie']) {
      proxyRes.headers['set-cookie'] = proxyRes.headers['set-cookie'].map(cookie => {
        return cookie.replace(/domain\=.+?;/, '');
      });
    }
  });
}
 `

**Comment by devilwjp** [comment]
@xiaobc1234 报的什么错

**Comment by xiaobc1234** [comment]
> @xiaobc1234 你截图中的错，就是把react的jsx以vue的方式去解析了，你的react组件是放在什么目录下的，默认必须放在react_app目录下、

哦，我这没有react_app目录，组件是放在src/components/react-comp 下面的

**Comment by devilwjp** [comment]
@xiaobc1234 嗯，如果想改变放置的目录规则，就需要配置一下veaury的vite插件
