### ISSUE TITLE
Warning :  ReactDOM.render is no longer supported in React 18

### ISSUE THREAD

**Issue by meshwara** [devilwjp/veaury#14]
I'm using veaury to use React component in Vue 3 project. It is running OK, but with warning like this :

`react-dom.development.js:86 Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
`
Please help.

**Comment by devilwjp** [comment]
@meshwara 
This is just a friendly warning, don't worry, the current version of veaury still uses ReactDom.render to create applications in order to support both react 17 and 18.

**Comment by meshwara** [comment]
Thank you
