### ISSUE TITLE
How to use with other vite plugins?

### ISSUE THREAD

**Issue by dasmikko** [devilwjp/veaury#16]
I'm trying to use vite-plugin-pages, with veaury, but it seems like veauryVitePlugins overrides all plugins i set. 

```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import Pages from "vite-plugin-pages";
import veauryVitePlugins from 'veaury/vite/index'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    Pages(),
    veauryVitePlugins({
      type: 'vue',
    }),
  ],
  server: {
    port: 8080
  },
})
```

**Comment by devilwjp** [comment]
The veauryVitePlugins will only cover vue and react plugins, other plugins will not be affected.  
The actual function of the veauryVitePlugin is to return an array of plugins, as follows:   
```js
[
  // from @vitejs/plugin-vue
  vue(),
  // from @vitejs/plugin-react
  react({
    babel: {
      // Default vuejsx plugin is off
      plugins: [['@vue/babel-plugin-jsx', false]],
      overrides: [{
         exclude: [/[/\\]react_app[\\/$]+/],
         plugins: ['@vue/babel-plugin-jsx']
      }]
    }
  })
]
```

**Comment by devilwjp** [comment]
@dasmikko 
You can try to execute `vite-plugin-pages` after the veauryVitePlugin

**Comment by devilwjp** [comment]
@dasmikko 
`vite-plugin-pages` error when using both vue and react plugins

**Comment by devilwjp** [comment]
@dasmikko 
You must set the configuration of `vite-plugin-pages` and specify `resolver` to be `vue`, `react` or `solid`, for example the following code:  
```js
Pages({resolver: 'vue'})
```

**Comment by dasmikko** [comment]
Hi, and thanks for the quick response!

Your last comment did the trick, and now vite builds!
