### ISSUE TITLE
Vue 2.7 Support

### ISSUE THREAD

**Issue by engrpatel21** [devilwjp/veaury#19]
With vue 2.7 introducing vue3 features like vite and script setup, do you plan on having 2.7 support for veaury?

**Comment by devilwjp** [comment]
About Vue2, you can use `vuereact-combined` or `vuera`.  And about `vite`, you can still use `veaury/vite`.

**Comment by devilwjp** [comment]
Because `veaury/vite` does not have to be used with `veaury`, `veaury/vite` is just a packaging configuration for vue's vite plugin and react's vite plugin.

**Comment by social-uni** [comment]
您好怎么样了

**Comment by devilwjp** [comment]
@alamhubb 不会支持vue2
