### ISSUE TITLE
veaury.d.ts文件添加函数参数的类型

### ISSUE THREAD

**Issue by luoxiaozero** [devilwjp/veaury#28]
版本: 2.2.5

tsc 打包时不通过，我只能去修改 tsconfig.json 文件。

是否可以在 https://github.com/devilwjp/veaury/blob/master/types/veaury.d.ts 文件的 52 行 ReactMissVueOptions 参数添加个类型，比如 any。

![7d07a529a83f41f237ee511c7c2c53b](https://user-images.githubusercontent.com/48741584/183298769-aba5382a-9072-445a-93ea-aace0a2f9e7f.png)

**Comment by luoxiaozero** [comment]
ReactMissVueOptions 如果是个 interface 的话，是否可以添加个参数名

**Comment by luoxiaozero** [comment]
我去看了下源码，可以改为这样

```ts
export const creatReactMissVue: (reactMissVueOptions: ReactMissVueOptions) => createReactMissVueReturn;
```

**Comment by devilwjp** [comment]
@luoxiaozero 
确实，这个地方出错了，我升级一个版本

**Comment by devilwjp** [comment]
@luoxiaozero 
veaury@2.2.6 已修复这个问题

**Comment by luoxiaozero** [comment]
好的
