### ISSUE TITLE
use React in Vue:  Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: symbol.

### ISSUE THREAD

**Issue by maxwls** [devilwjp/veaury#29]
![image](https://user-images.githubusercontent.com/4974265/183386609-f6ad43ab-9551-44dd-95f3-edcd2cc6353e.png)
错误发生在加载ReactApp组件（包含mobx-react Provider Injector)

App.vue引入Login.vue组件：
![image](https://user-images.githubusercontent.com/4974265/183387286-c72d7155-38dc-4fde-97d9-1e9058215e2e.png)

Login.vue引入了ReactApp组件
```
<template>
  <LoginVue></LoginVue>
</template>

<script lang="js">
import ReactApp from '../react/ReactApp';
import { applyPureReactInVue } from "veaury";

export default {
  name: 'login-vue',
  components: {
    LoginVue: applyPureReactInVue(ReactApp)
  }
}
</script>
```
ReactApp.js：
```
import React, { Component } from 'react';
import { Provider } from 'mobx-react';
// import store from "./store";
import { store } from 'osp-react-base';
import Router from './router';
class App extends Component {
    constructor(props) {
        super(props);
        window.afterApplicationInited && window.afterApplicationInited();
    }

    componentDidMount() {
        window.onLoginSuccess && window.onLoginSuccess();
    }

    render() {
        return (
            <Provider {...store}>
                <Router />
            </Provider>
        );
    }
}

export default App;
```
Router组件：
![image](https://user-images.githubusercontent.com/4974265/183388115-3138d95e-c606-444f-a061-28e744df79ae.png)

**Comment by devilwjp** [comment]
@maxwls 
初步判断和react-router没关系，感觉是class组件的问题，我复现下这个问题

**Comment by maxwls** [comment]
我感觉是mobx-react的Provider和Inject的问题。尝试过mobx-react-lite的模式：使用react.createContext再用mobx的observer就没这个错误。但是旧代码中mobx-react的Provider大量被使用，需要兼容。。。

**Comment by devilwjp** [comment]
@maxwls 
我晚上先定位下，我只要手动创建一个Provider，并且放在class组件内部，看看是否能复现问题

**Comment by devilwjp** [comment]
@maxwls 你的这个问题我定位到了，不是我的问题，是你的项目对于react jsx的编译不支持简易的Fragment方式`<>.....</>`
![image](https://user-images.githubusercontent.com/38802722/183417947-7b5b5847-efe4-49b1-b665-3b4de3cfe003.png)
可以考虑将`<>`替换成`<Fragment>`

**Comment by devilwjp** [comment]
@maxwls 经过更深一步的分析，`<>`是被vue的babel插件编译成了vue的Fragment，而react的babel插件忽略了这个标签的编译

**Comment by devilwjp** [comment]
@maxwls 
此问题已解决，升级到veaury@2.2.7
更新`babel.config.js`，注释`@vue/cli-plugin-babel/preset`  

babel.config.js
```js
module.exports = {
  presets: [
    // Turn off '@vue/cli-plugin-babel/preset'
    // '@vue/cli-plugin-babel/preset',
    // veary babel preset
    'veaury/babel/ReactPreset'
  ]
}
```

**Comment by maxwls** [comment]
> @maxwls 你的这个问题我定位到了，不是我的问题，是你的项目对于react jsx的编译不支持简易的Fragment方式`<>.....</>` ![image](https://user-images.githubusercontent.com/38802722/183417947-7b5b5847-efe4-49b1-b665-3b4de3cfe003.png) 可以考虑将`<>`替换成`<Fragment>` 这个错是直接jsx编译出错了，导致createElement无法识别编译后的对象

这个方式可行。

**Comment by maxwls** [comment]
> @maxwls 此问题已解决，升级到veaury@2.2.7 这个问题只会出现在基于webpack构建的项目里 原因是之前使用了老的`babel-plugin-transform-react-jsx`不支持对React Fragment简写的编译 现在替换成了`babel-preset-react-app`，需要在`babel.config.js`中注释`@vue/cli-plugin-babel/preset`
> 
> babel.config.js
> 
> ```js
> module.exports = {
>   presets: [
>     // Turn off '@vue/cli-plugin-babel/preset'
>     // '@vue/cli-plugin-babel/preset',
>     // veaury babel preset
>     'veaury/babel/ReactPreset'
>   ]
> }
> ```
升级后，同样的错误继续存在。
babel.config.js:
![image](https://user-images.githubusercontent.com/4974265/183547521-ecb5e0d3-8a24-49c8-8171-b935554a6139.png)
veaury版本：
![image](https://user-images.githubusercontent.com/4974265/183547611-5ade38c3-e1ff-4559-a8c6-d2d43e865d6a.png)
vue.config.js:
![image](https://user-images.githubusercontent.com/4974265/183547834-a8bd3618-7004-4367-8782-95052a3600fc.png)

**Comment by devilwjp** [comment]
@maxwls 还是先定位下问题吧，强制改成<Fragment>后是否就好了？

**Comment by maxwls** [comment]
> @maxwls 此问题已解决，升级到veaury@2.2.7 这个问题只会出现在基于webpack构建的项目里 原因是之前使用了老的`babel-plugin-transform-react-jsx`不支持对React Fragment简写的编译 现在替换成了`babel-preset-react-app`，需要在`babel.config.js`中注释`@vue/cli-plugin-babel/preset`
> 
> babel.config.js
> 
> ```js
> module.exports = {
>   presets: [
>     // Turn off '@vue/cli-plugin-babel/preset'
>     // '@vue/cli-plugin-babel/preset',
>     // veaury babel preset
>     'veaury/babel/ReactPreset'
>   ]
> }
> ```

完美解决。注意：vue工程中的react组件代码默认放在react_app目录下。
