### ISSUE TITLE
vue3引入react17组件构建报错，babel配置按此库文档操作的。有知道的大佬回复回复嘛

### ISSUE THREAD

**Issue by Candidade** [devilwjp/veaury#31]
![企业微信截图_16602889176586(1)](https://user-images.githubusercontent.com/62602475/184822975-7f1110e1-2c11-48ac-8767-06ada4d0f232.png)
![企业微信截图_16602891301073(1)](https://user-images.githubusercontent.com/62602475/184822994-f5b5e0a6-ca9e-4c88-a803-a81f24a54490.png)

**Comment by devilwjp** [comment]
@Candidade 你这个组件是怎么引入的？vue里使用react组件的代码能贴一下吗？

**Comment by Candidade** [comment]
这边麻烦看看，
![企业微信截图_16602888693216(1)](https://user-images.githubusercontent.com/62602475/184823732-da25de74-7492-45a2-b892-ffca962cb685.png)
![企业微信截图_16602888899424(1)](https://user-images.githubusercontent.com/62602475/184823741-ebf4844e-a58d-405a-ba96-777f04604982.png)

**Comment by Candidade** [comment]
![image](https://user-images.githubusercontent.com/62602475/184824058-92c42ac5-8d2a-49e0-af03-7aa4bc88ed84.png)
这是pack.json

**Comment by devilwjp** [comment]
@Candidade 你的问题很明确了，就是你的react文件放错目录了，你是vite项目还是webpack项目？

**Comment by devilwjp** [comment]
@Candidade 由于你的react文件放错了目录，导致react的jsx被使用了vue的jsx进行了编译，编译成了VNode而不是ReactNode

**Comment by Candidade** [comment]
webpack的，这个文件目录有讲究？？我看此库文档babel里面可以单独配路径，我没配路径 ,直接同目录./引用了

**Comment by devilwjp** [comment]
@Candidade 
参考这个项目的说明 [How to configure React in the Vue project from '@vue/cli'](https://github.com/devilwjp/veaury/tree/master/dev-project-vue3)  
建议你在你的babel.config.js里配置`veaury/babel/ReactPreset`，并且默认只对`react_app`目录下的jsx启用

**Comment by Candidade** [comment]
我更改了目录 ，没了报错，请看图
![image](https://user-images.githubusercontent.com/62602475/184826885-5c6064ad-2982-45ff-a4d7-3aea68a0ffad.png)
![image](https://user-images.githubusercontent.com/62602475/184826958-01b5e13a-2129-479f-a06b-ea377ae1653d.png)

**Comment by devilwjp** [comment]
这是你代码错误了，你都注释掉了  
![image](https://user-images.githubusercontent.com/38802722/184827518-1a4d8f83-5d18-4fac-9390-4183904536bb.png)

**Comment by devilwjp** [comment]
这是你的代码错误，你的把BasicPure注释掉了  
![Uploading image.png…]()

**Comment by Candidade** [comment]
刚刚上面有点问题，直接看此图
![image](https://user-images.githubusercontent.com/62602475/184827720-5e9ffeda-a9c1-4264-a5c3-20b745105971.png)

**Comment by Candidade** [comment]
okok，可以啦 ，感谢大佬
