### ISSUE TITLE
vue3使用jsx模板，引入react17组件报错问题，麻烦知晓大佬看一下问题

### ISSUE THREAD

**Issue by Candidade** [devilwjp/veaury#32]
![image](https://user-images.githubusercontent.com/62602475/184834142-a30bcd27-97f2-404f-bde4-9710bbe81373.png)
![image](https://user-images.githubusercontent.com/62602475/184834190-c7b9be29-92a4-494a-92eb-872e1caa371c.png)
![image](https://user-images.githubusercontent.com/62602475/184834286-f0a2aade-67a9-46a6-ad9c-37b847f0e2c9.png)

**Comment by Candidade** [comment]
![image](https://user-images.githubusercontent.com/62602475/184834436-6d355b76-9f18-44b4-9b57-d09394964e9d.png)
貌似没构建react

**Comment by devilwjp** [comment]
你的Test组件并没有使用`applyReactInVue`包装，直接用在vue的jsx里，肯定是不行的
![Uploading image.png…]()

**Comment by Candidade** [comment]
昂纳昂，我都不想说自己了，哎 麻烦了麻烦了，求删帖

**Comment by devilwjp** [comment]
没事，我关闭就好
