### ISSUE TITLE
在vue中我引入一个react组件，报了一个这种错误veaury.esm.js?b318:formatted:1697 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'apply')

### ISSUE THREAD

**Issue by HongYunser** [devilwjp/veaury#34]
![image](https://user-images.githubusercontent.com/22743566/190544800-3e660d52-98cd-442a-86fe-28b2dad30e7f.png)
![image](https://user-images.githubusercontent.com/22743566/190544927-ec2f7538-c2c4-419d-9fe7-3417a676ce52.png)
以上两种用法都会报
![Uploading image.png…]()
这个错误，请问是什么情况导致的呢，有什么解决方案嘛？

**Comment by devilwjp** [comment]
@HongYunser 错误信息的截图是否没有上传成功？

**Comment by devilwjp** [comment]
@HongYunser 图二的方式肯定是不对的，异步组件要用lazyPureReactInVue，图一的方式应该没有问题，关键我看不到你的报错截图，麻烦重新上传一下

**Comment by HongYunser** [comment]
![image](https://user-images.githubusercontent.com/22743566/190565623-6f5ff25f-fe4b-4094-b41a-0a59b2f13007.png)

**Comment by HongYunser** [comment]
@devilwjp 不好意思，刚才应该是没上传成功，报错图中的信息和标题上描述的一样

**Comment by devilwjp** [comment]
@HongYunser 只有`osp-react-comps/lib/components/allapps`使用上有这个报错是吗？

**Comment by HongYunser** [comment]
@devilwjp 是的。然后我用lazyPureReactInVue这个方式试了一下，又出现个新的问题
![image](https://user-images.githubusercontent.com/22743566/190568062-f84fe8d3-bce9-452f-82ff-86d3b91ad564.png)
![image](https://user-images.githubusercontent.com/22743566/190568096-538b12dc-dead-4af2-a1be-968e88fedd86.png)

**Comment by devilwjp** [comment]
@HongYunser 这个看上去像是你公司内部npm源安装的组件，能提供一下这个组件包吗？

**Comment by HongYunser** [comment]
@devilwjp 这个就是个普通的react组件
![image](https://user-images.githubusercontent.com/22743566/190568799-22f20436-6139-49e8-acb3-735e3b28f7c2.png)

**Comment by devilwjp** [comment]
@HongYunser 好的，就是个普通的class组件，我定位一下，你另外两个正常的组件是函数组件吗？

**Comment by HongYunser** [comment]
@devilwjp 这个几个引用都有问题
![image](https://user-images.githubusercontent.com/22743566/190570014-312a5900-ea9d-41d0-acf1-d8b757bd2630.png)
我在另一个文件里面引用的类似的组件
![image](https://user-images.githubusercontent.com/22743566/190570536-af755bcb-eb4f-4184-9576-740efc786059.png)
这样的就没有报错。

**Comment by HongYunser** [comment]
> @devilwjp 是的。然后我用lazyPureReactInVue这个方式试了一下，又出现个新的问题 ![image](https://user-images.githubusercontent.com/22743566/190568062-f84fe8d3-bce9-452f-82ff-86d3b91ad564.png) ![image](https://user-images.githubusercontent.com/22743566/190568096-538b12dc-dead-4af2-a1be-968e88fedd86.png)

@devilwjp 我用lazyPureReactInVue这个方法试了一下，这个是出现的新的错误

**Comment by devilwjp** [comment]
@HongYunser 我理解一下，就是用mobx包装一个普通的react组件是吗？

**Comment by devilwjp** [comment]
@HongYunser 你项目的构建工具是webpack还是vite?

**Comment by HongYunser** [comment]
> @HongYunser 你项目的构建工具是webpack还是vite?

webpack

**Comment by devilwjp** [comment]
@HongYunser 好的，今天晚上，我会排查一下你的情况

**Comment by HongYunser** [comment]
> @HongYunser 我理解一下，就是用mobx包装一个普通的react组件是吗？
emmm- -其实那个地方就是把那个AppState注入到那个react组件中了，不能算是包装吧

**Comment by HongYunser** [comment]
> @HongYunser 好的，今天晚上，我会排查一下你的情况

好的，辛苦您了。多谢

**Comment by devilwjp** [comment]
@HongYunser 你再替我做一个测试，你通用使用mobx注入到一个你项目中的组件，不用通过npm，然后把react组件放在react_app目录下，然后你在vue组件中引入，看看是否报相同错误

**Comment by HongYunser** [comment]
> @HongYunser 你再替我做一个测试，你通用使用mobx注入到一个你项目中的组件，不用通过npm，然后把react组件放在react_app目录下，然后你在vue组件中引入，看看是否报相同错误

好的，稍等

**Comment by HongYunser** [comment]
@devilwjp 
![image](https://user-images.githubusercontent.com/22743566/190577778-506cbf25-e929-4f4b-98da-18a31d27acbc.png)
是的，还是同样的错误
![image](https://user-images.githubusercontent.com/22743566/190577925-75458227-27dc-4f86-8e8b-c04cebde6ab2.png)

**Comment by devilwjp** [comment]
截图里不能这么用，异步必须用lazyReactInVue，而且不能使用loadable

**Comment by devilwjp** [comment]
@HongYunser 
![image](https://user-images.githubusercontent.com/38802722/190578340-75ae4508-6b7f-439e-b093-514c30bf82a2.png)

**Comment by HongYunser** [comment]
> @HongYunser ![image](https://user-images.githubusercontent.com/38802722/190578340-75ae4508-6b7f-439e-b093-514c30bf82a2.png)

ok，我试试

**Comment by devilwjp** [comment]
@HongYunser 或者别用异步，先用同步，先看问题

**Comment by devilwjp** [comment]
@HongYunser react组件要放在react_app目录里

**Comment by HongYunser** [comment]
![image](https://user-images.githubusercontent.com/22743566/190579091-a2f88b27-69d1-4390-bc3b-57eee50a081b.png)
![image](https://user-images.githubusercontent.com/22743566/190579122-056ecb33-31c4-462b-b323-ddcd68e4ab63.png)
同步引用也是这个错误。我觉得可能跟这个inject注入有点关系，刚看了下没报错的react组件，
![image](https://user-images.githubusercontent.com/22743566/190579450-069d4b50-d744-4a55-a032-ec2b04797a9d.png)
是没有inject注入的

**Comment by devilwjp** [comment]
你的vue.config.js或者webpack.config.js是否使用了veaury/babel/ReactPreset?

**Comment by HongYunser** [comment]
> 

恩，这个在
![image](https://user-images.githubusercontent.com/22743566/190581063-6866154b-1a1f-4181-9fff-dbca7643c821.png)
这个文件中有配置

**Comment by devilwjp** [comment]
@HongYunser 你看一下英文注释

**Comment by devilwjp** [comment]
@HongYunser 问题找到了，首先你优先过滤了node_modules，所以你走不到下面osp的目录判断部分

**Comment by devilwjp** [comment]
@HongYunser 你可以尝试把node_modules的部分也`return filename`试试，并且如果是你项目src目录里的组件，你添加一下src到你的正则表达式里，你再试试

**Comment by HongYunser** [comment]
![image](https://user-images.githubusercontent.com/22743566/190583220-71817d05-51c7-47be-95ac-692da8e184bb.png)
应该不是，我创建了一个react_app的目录，结果还是一样- -

**Comment by devilwjp** [comment]
@HongYunser allapps.jsx能否改成一个很纯的react组件？然后再使用mobx

**Comment by devilwjp** [comment]
比如改成
```jsx
export default function(){
  return <div>test</div>
}
```

**Comment by HongYunser** [comment]
![image](https://user-images.githubusercontent.com/22743566/190584973-79a63e57-248c-472f-86ab-25d99de71ddf.png)
改成这样之后，还是一样的c错误信息

**Comment by devilwjp** [comment]
@HongYunser 太棒了，然后去掉mobx就好了是吗？

**Comment by HongYunser** [comment]
我尝试一下去吊mobx试试

> @HongYunser 太棒了，然后去掉mobx就好了是吗？

**Comment by HongYunser** [comment]
![image](https://user-images.githubusercontent.com/22743566/190586343-fb93e2f1-2dd7-4676-9993-c0a60b9c74b5.png)
![image](https://user-images.githubusercontent.com/22743566/190586387-fff404fc-9393-42ff-a000-77d5083db662.png)
越来越扑朔迷离了= =改成这样还是有错误
![image](https://user-images.githubusercontent.com/22743566/190586489-ab55f086-e088-4199-8e85-44e13926d3e3.png)

**Comment by devilwjp** [comment]
@HongYunser 你veaury是什么版本？

**Comment by HongYunser** [comment]
2.2.7

> @HongYunser 你veaury是什么版本？

**Comment by devilwjp** [comment]
@HongYunser 你确认是2.2.7吗？我这边尝试了下是没问题的

**Comment by HongYunser** [comment]
![image](https://user-images.githubusercontent.com/22743566/190615502-fd8dec92-1489-4f61-9e52-f1781750fcea.png)
是开发环境

**Comment by devilwjp** [comment]
@HongYunser 如果你最纯的react组件都无法使用，那么可能是你项目有自身的特殊性了，方便提供一个你项目的副本吗，只放一个vue组件和一个react组件

**Comment by HongYunser** [comment]
emmm，公司代码，领导不让外露- -难受了呀。。。

**Comment by devilwjp** [comment]
@HongYunser 我给你一个demo，你参照我的demo看你项目的问题

**Comment by HongYunser** [comment]
> @HongYunser 我给你一个demo，你参照我的demo看你项目的问题

好的，你发到我邮箱就行了，多谢。hongyun_sir@163.com

**Comment by devilwjp** [comment]
@HongYunser 
拉取这个仓库的mobx-react-test分支(https://github.com/devilwjp/veaury/tree/mobx-react-test)  
进入dev-project-vue3目录，然后安装项目（`yarn`或者`npm i`），然后`npm run serve`，调试`dev-project-vue3/src/app.vue`和`dev-project-vue3/src/react_app/Test1.js`

**Comment by devilwjp** [comment]
@HongYunser 
由于长时间没有对这个问题进行反馈，所以先进行关闭，后期如果发现仍有问题可以再打开此问题

**Comment by HongYunser** [comment]
不好意思，最近去忙其他的东西了，这个问题已经解决了，是我引用的问题，忘了给您恢复，抱歉。后续有其他问题再找您请教，多谢帮助！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "devilwjp/veaury"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月23日(星期五) 凌晨3:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [devilwjp/veaury] 在vue中我引入一个react组件，报了一个这种错误veaury.esm.js?b318:formatted:1697 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'apply') (Issue #34)





 
@HongYunser
 由于长时间没有对这个问题进行反馈，所以先进行关闭，后期如果发现仍有问题可以再打开此问题
