### ISSUE TITLE
打包后运行报错 Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by qwq0833** [devilwjp/veaury#35]
### 问题

开发环境下一切正常，生产环境下报错 **Uncaught ReferenceError: require is not defined**

### 操作路径

1. 创建一个项目：`npm init vue@latest`
2. 安装依赖：`npm i -S veaury @rainbow-me/rainbowkit wagmi ethers`
3. 修改 App.vue（见代码块）
4. 检查开发环境（正常）
<img width="889" alt="image" src="https://user-images.githubusercontent.com/51783528/190564399-31c1e0b3-b300-4283-a9e4-42e63f725e40.png">
5. 打包项目：`npm run build`
6. 预览项目：`npm run preview`
<img width="804" alt="image" src="https://user-images.githubusercontent.com/51783528/190564550-b77d3a5f-744b-4d25-a4d1-66006642656e.png">

### app.vue
```vue
<script lang="ts" setup>
import { applyReactInVue, applyPureReactInVue } from 'veaury';
import '@rainbow-me/rainbowkit/styles.css';

import { getDefaultWallets, RainbowKitProvider } from '@rainbow-me/rainbowkit';
import { chain, configureChains, createClient, WagmiConfig } from 'wagmi';
import { alchemyProvider } from 'wagmi/providers/alchemy';
import { publicProvider } from 'wagmi/providers/public';
import { ConnectButton } from '@rainbow-me/rainbowkit';

const { chains, provider } = configureChains(
  [chain.mainnet, chain.polygon, chain.optimism, chain.arbitrum],
  [alchemyProvider({ apiKey: undefined }), publicProvider()]
);

const { connectors } = getDefaultWallets({
  appName: 'My RainbowKit App',
  chains
});

const wagmiClient = createClient({
  autoConnect: true,
  connectors,
  provider
});

const ReactRainbowKitProvider = applyReactInVue(RainbowKitProvider);
const ReactWagmiConfig = applyReactInVue(WagmiConfig);
const ReactConnectButton = applyPureReactInVue(ConnectButton);
</script>

<template>
  <div>
    <ReactWagmiConfig :client="wagmiClient">
      <ReactRainbowKitProvider :chains="chains"> <ReactConnectButton /> </ReactRainbowKitProvider>
    </ReactWagmiConfig>
  </div>
</template>
```

### 依赖版本

```json
{
    "@rainbow-me/rainbowkit": "^0.5.3",
    "pinia": "^2.0.21",
    "veaury": "^2.3.6",
    "vue": "^3.2.39",
    "vue-router": "^4.1.5",
    "wagmi": "^0.6.6"
  }
```

### 错误溯源

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/51783528/190564650-b19ff306-9022-467a-8a9f-d5f95c3f1c92.png">

**Comment by devilwjp** [comment]
@qwq0833 你的构建工具是webpack还是vite?

**Comment by qwq0833** [comment]
> @qwq0833 你的构建工具是webpack还是vite?

目前 cli 最新版用的是 vite，试了一下所有的 vite 项目基本都有这个问题

**Comment by devilwjp** [comment]
@qwq0833 好的，这个问题我定位一下，你可以先降级到2.3.1，规避这个问题

**Comment by qwq0833** [comment]
> @qwq0833 好的，这个问题我定位一下，你可以先降级到2.3.1，规避这个问题

2.3.1 可以，非常感谢！

**Comment by devilwjp** [comment]
@qwq0833 或者可以使用`vite-plugin-require-transform`，因为2.3.2之后的版本会判断react版本，使用了require进行动态引入react，这个问题我之后会处理

**Comment by devilwjp** [comment]
@qwq0833 我发现用vite@2.9.14 打包是可以的

**Comment by devilwjp** [comment]
@qwq0833 已修复，version 2.3.7
