### ISSUE TITLE
Vite v3.0.2  报错

### ISSUE THREAD

**Issue by XiaoBaiClassmate** [devilwjp/veaury#36]
version:2.3.7

vite.config.js;
import veauryVitePlugins from 'veaury/vite';

再运行 npm run dev

```
 Directory import 'D:\xxxx\node_modules\veaury\vite' is not supported resolving ES modules imported from D:xxxx\vite.config.js.mjs
``

**Comment by devilwjp** [comment]
@XiaoBaiClassmate
如果你遇到这个错误，可以将引入方式替换为`import veauryVitePlugins from 'veaury/vite/index.js';

`
