### ISSUE TITLE
转换 amis 控件报错

### ISSUE THREAD

**Issue by iiixxxiii** [devilwjp/veaury#37]
![image](https://user-images.githubusercontent.com/2424593/192425757-d06fe6ab-2e94-42a0-b5c5-cdb32b197ed3.png)
![image](https://user-images.githubusercontent.com/2424593/192426124-69bade13-9b1c-4e87-8aec-fdb2a9c6712d.png)

**Comment by devilwjp** [comment]
@iiixxxiii 请提供一个完整的例子，而不仅仅是截图

**Comment by devilwjp** [comment]
@huoxiangdong 提供一个完整的例子给我吧

**Comment by huoxiangdong** [comment]
https://github.com/boneVidy/vite-amis/blob/main/src/polyfill-amis.ts

**Comment by devilwjp** [comment]
@huoxiangdong 那应该是amis自己的问题了，不兼容vite，需要polyfill

**Comment by gaopengpian** [comment]
same error for me

**Comment by devilwjp** [comment]
@gaopengpian
Vite does not support the use of dynamic require，this is amis own problem.

**Comment by gaopengpian** [comment]
> 参见 `https://github.com/boneVidy/vite-amis/blob/main/src/polyfill-amis.ts` polyfll一下，应该可以解决

@devilwjp 这个方法似乎无效，有其他解决的思路吗？

**Comment by devilwjp** [comment]
@gaopengpian 这个方法不是我提供的，vite是不支持动态引入require的，需要手动分析amis哪些动态引入了，然后手动配置到vite.config.js里，具体可以参考(#10 )
