### ISSUE TITLE
Failed to resolve import "virtual:generated-pages" 

### ISSUE THREAD

**Issue by JAVPHP** [devilwjp/veaury#40]
![1665974675851](https://user-images.githubusercontent.com/48326762/196078135-7aeb26b6-1415-4d04-ba41-3f764f4fc547.png)
![1665974772611](https://user-images.githubusercontent.com/48326762/196078338-f8238391-6148-4cbc-aac4-9ef5afbfc8db.png)

按照要求配置，但是报错
Failed to resolve import "virtual:generated-pages" from "src\router\index.ts". Does the file exist?
![image](https://user-images.githubusercontent.com/48326762/196078429-285adee5-0375-44bd-8a51-e87402df1374.png)

**Comment by devilwjp** [comment]
@JAVPHP 看上去好像不是veaury的问题，你不使用veauryVitePlugins，就没问题了嘛？
