### ISSUE TITLE
可以在vue项目中使用jsx/tsx文件吗？同时react_app目录里面的jsx/tsx文件编译走的react的流程

### ISSUE THREAD

**Issue by OPBR** [devilwjp/veaury#42]
vue3的vite项目里面原来配置了`@vitejs/plugin-vue-jsx`插件，支持了JSX/TSX文件，现在想要引入react应该要怎么做不影响原来vue中的JSX/TSX文件呢

**Comment by devilwjp** [comment]
@OPBR 完全可以

**Comment by OPBR** [comment]
THX
