### ISSUE TITLE
Using tsx file inside vue app

### ISSUE THREAD

**Issue by Lafa02** [devilwjp/veaury#45]
#Hi I'm trying to use some tsx components inside my react app, but the console gives me a weird error
Note: I'm using quasar with vue
my Hello.react.tsx
import React from 'react';
`
export default const HelloReact = (name: string) => {
  return <div>Hello {name}, I am a React component</div>;
}
`
my  app.vue
`<template>
    <HelloReact name="ciao" />
</template>

<script lang="ts">
import { applyReactInVue } from 'veaury';
import { defineComponent } from 'vue';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import HelloReact from './Hello.react.tsx';
export default defineComponent({
  components: {
    HelloReact: applyReactInVue(HelloReact),
  },
  data() {
    return {
    };
  },
});
</script>

this is my """webpack""":
`
![image](https://user-images.githubusercontent.com/30123016/200558025-239c6794-2f5d-4c3c-84aa-8c54af6b7505.png)

and this is the error
![image](https://user-images.githubusercontent.com/30123016/200558110-da10e259-f441-4c07-a9e9-1b429fe01b30.png)
I'm doing something wrong for sure, but I have no idea what

**Comment by devilwjp** [comment]
@Lafa02 
The example you provided does not show the template part of the vue component. Your error message means that an invalid child was passed in. The error may exist in the template part.

**Comment by Lafa02** [comment]
I'm so stupid, sorry, thank you so much!
