### ISSUE TITLE
using forwardRef component in Vue 3

### ISSUE THREAD

**Issue by anhcuong203** [devilwjp/veaury#46]
Hi. I have a Vue parent and forwardRef React child. I get data directly via useImperativeHandle but data never updated. Do you have any idea?

**Comment by devilwjp** [comment]
@anhcuong203 
The data obtained through ref will not automatically trigger the update, both vue and react behave like this.

**Comment by anhcuong203** [comment]
if I use useImperativeHandle like this
useImperativeHandle(
    ref,
    () => ({
        getData: () => {
          return data;
        }
    }),
    [data]
);

data is always up to date when I call getData function through ref. data not updated only in case I use Vue component as parent

**Comment by devilwjp** [comment]
@anhcuong203 
The `data` in the example you provided is the state defined inside the react component, or is it passed in by the parent's vue component

**Comment by anhcuong203** [comment]
Vue component:
`<template>
  <div class="gantt-wrapper">
    <ChildrenForwardRefReact ref="childRef" />
    <button @click="getData">get data</button>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { ChildrenForwardRef } from '@/../react_app/Lab';
import { applyReactInVue } from 'veaury';
const ChildrenForwardRefReact = applyReactInVue(ChildrenForwardRef);

const childRef = ref();
const getData = () => {
  console.log('get data');
  const data = childRef.value.getData();
  console.log(data);
};
</script>
`

React child component:
`import React, { forwardRef, useImperativeHandle, useState } from 'react';

export const ChildrenForwardRef = forwardRef((props, ref) => {
  const [counter, setCounter] = useState(0);

  const increase = () => {
    setCounter(counter + 1);
  };

  useImperativeHandle(
    ref,
    () => ({
      getData: () => {
        return counter;
      }
    }),
    [counter]
  );

  return (
    <div>
      <button onClick={increase}>add</button>
      <div>{counter}</div>
    </div>
  );
});
`

**Comment by anhcuong203** [comment]
Vue parent component:
```js
<template>
  <div class="gantt-wrapper">
    <ChildrenForwardRefReact ref="childRef" />
    <button @click="getData">get data</button>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { ChildrenForwardRef } from '@/../react_app/Lab';
import { applyReactInVue } from 'veaury';
const ChildrenForwardRefReact = applyReactInVue(ChildrenForwardRef);

const childRef = ref();
const getData = () => {
  console.log('get data');
  const data = childRef.value.getData();
  console.log(data);
};
</script>

```

React child component:

```js
import React, { forwardRef, useImperativeHandle, useState } from 'react';

export const ChildrenForwardRef = forwardRef((props, ref) => {
  const [counter, setCounter] = useState(0);

  const increase = () => {
    setCounter(counter + 1);
  };

  useImperativeHandle(
    ref,
    () => ({
      getData: () => {
        return counter;
      }
    }),
    [counter]
  );

  return (
    <div>
      <button onClick={increase}>add</button>
      <div>{counter}</div>
    </div>
  );
});

```

**Comment by devilwjp** [comment]
@anhcuong203 
Replace `childRef.value.getData();` with `childRef.value.__veauryReactRef__.getData()`

**Comment by anhcuong203** [comment]
@devilwjp thank you!

**Comment by jokerleon** [comment]
> @anhcuong203 Replace `childRef.value.getData();` with `childRef.value.__veauryReactRef__.getData()`
> 
> It is stated in the documentation that to get the ref of react use `__veauryReactRef__`

你好，我使用pure模式获取的ref中没有这个字段，请教下可能是什么原因？
