### ISSUE TITLE
关于文档中 ‘在 Vue 组件中注入 React hooks的用法’ 这一段的疑惑

### ISSUE THREAD

**Issue by e274426380** [devilwjp/veaury#48]
我读下来的理解是：

- 在 Vue 组件中使用 React hooks
- 先建立一个props为reactRouter的vue组件
- 然后单独写一个ts文件，在里面导入刚才写好的vue组件，并使用 veaury的applyVueInReact 作为转换。

但是然后呢？
这个ts文件写完后我该怎么办？
还有一点语义上的疑惑，如下：
‘**在 Vue 组件中注入 React hooks的用法**’标题开头底下的‘React 应用使用 Vue 组件，以下例子是在这个Vue组件中使用react-router’
这段话着实令人疑惑。
这段话讲的不是应该是在Vue组件里使用React hook吗，为什么又变成了react使用vue组件

**Comment by devilwjp** [comment]
@e274426380 
vue组件中，使用react hooks，前提是这个vue组件应该被用在react项目中或者至少被一个react组件使用，否则使用react hooks是没有意义的

```jsx
// 这是一个React组件的例子，并且要使用一个AboveVueComponent的Vue组件
import React from 'react';
import { applyVueInReact } from 'veaury'
import { useLocation, useNavigate } from 'react-router-dom'
import AboveVueComponent from './AboveVueComponent'

// Vue组件(AboveVueComponent)被转换为react组件，并且这个vue组件可以使用react-router，vue组件直接使用props.reactRouter使用react-router
const ReactComFromVue = applyVueInReact(AboveVueComponent, {
  useInjectPropsFromWrapper(reactProps) {
    // React hooks can be used in this function
    // Use the hooks of react-router-dom
    const location = useLocation()
    const navigate = useNavigate()

    // The returned object will be passed to the Vue component as props
    return {
      reactRouter: {
        navigate,
        location
      }
    }
  }
})

export default function DemoReactCom () {
  return <ReactComFromVue />
}

```

**Comment by e274426380** [comment]
> 

我实际的问题是现在需要接入一个react的npm包，里面包含一个react的登录按钮和包裹app.vue用的Provider，里面还提供了一个hooks的api接口用于获取登录后的各种信息。
使用veaury转换react组件没有问题。
如果在转换后，直接使用这个包的hooks会提示
`Cannot read properties of null (reading 'useContext')`

现在就是不知道如何才能转换这个react的api接口在vue中使用

**Comment by devilwjp** [comment]
@e274426380 
以你的描述，你是想在vue组件里直接使用react hooks，并且这个vue组件也是被vue应用或者组件使用的。并没有直接提供这样的用法，倒是对react是提供了`ReactMissVue`的功能，是可以直接在react组件中直接使用vue hooks的，但是并没有提供`VueMissReact`

不过也是有解决方案的，但是需要中转，首先需要使用`createCrossingProviderForVueInReact`  
https://github.com/devilwjp/veaury/blob/master/README_zhcn.md#createcrossingproviderforvueinreact-%E7%9A%84%E7%94%A8%E6%B3%95  
然后将`ReactRouterProviderForVue`组件再通过applyReactInVue转换成vue组件，套在你需要内部使用react hooks的vue组件之外

**Comment by e274426380** [comment]
@devilwjp 这是个不错的思路，我明天试试

**Comment by devilwjp** [comment]
@e274426380 我晚点给你一个例子

**Comment by devilwjp** [comment]
@e274426380 

```vue
<template>
  <ReactTestContextProviderInVue :value="contextValue">
    <HooksProviderInVue>
      <VueComponent/>
    </HooksProviderInVue>
  </ReactTestContextProviderInVue>

</template>

<script setup>
import {useContext, createContext} from 'react'
import {defineComponent, onMounted, onUnmounted, ref} from 'vue'
import {applyReactInVue, createCrossingProviderForVueInReact } from 'veaury'

// 创建一个React context
const ReactTestContext = createContext()
// 将React context的Provider转换为vue组件
const ReactTestContextProviderInVue = applyReactInVue(ReactTestContext.Provider)

// 创建一个跨技术栈到vue的react hooks和一个对应使用的react provider
const [useHooksInVue, HooksProvider] = createCrossingProviderForVueInReact(
    function() {
      return {
        // 将前面创建的React context的值暴露给vue，使用useContext hooks
        reactTestContext: useContext(ReactTestContext)
      }
    }
)
// 将HooksProvider转换为vue组件
const HooksProviderInVue = applyReactInVue(HooksProvider)

// 临时定义一个vue组件，组件里使用前面定义的vue hooks
const VueComponent = defineComponent({
  setup() {
    const {reactTestContext} = useHooksInVue()
    // 这里使用了vue的jsx
    return () => <div>{reactTestContext}</div>
  }
})

// 定义一个响应式的状态，用于React context的value
const contextValue = ref(Math.random())

let timer
onMounted(() => {
  clearTimeout(timer)
  timer = setInterval(() => {
    contextValue.value = Math.random()
  }, 1000)
})

onUnmounted(() => {
  clearTimeout(timer)
})
</script>

```

**Comment by e274426380** [comment]
@devilwjp 感谢你的例子和帮助，问题已经得到解决。
这个核心解决要点是必须将HooksProvider转换为Vue组件并且包裹在要使用hook的组件外面才能让vue组件获取react的hooks。
没有这个例子我还真不知道怎么办……
只不过有个小小的问题，我是在app.vue里进行的组件叠加。
一旦将VueMissReact组件放入app.vue，会导致页面在短暂的正常显示后进入异常的白屏状态，控制台倒是可以正常运行。（使用vue-router作为导航）
```
 <Provider >
       <VueMissReact >
            <router-view/>
        </VueMissReact >
    </Provider>
```
然后我将VueMissReact这个组件放入了一个主页的组件，问题就变成了里面的组件会疯狂刷新，每隔几秒就会自动刷新一次页面，不知道问题出在了哪里。。
```
<template>
    <VueMissReact >
        <div class="home-container">
            <Navigator/>
            <Public/>
            <PostList/>
        </div>
    </VueMissReact >
</template>
```

最后还是感谢你的帮助。

**Comment by devilwjp** [comment]
@e274426380 能提供一个出问题的例子吗。我复现下看看

**Comment by e274426380** [comment]
@devilwjp 项目地址：https://github.com/rightsdao/iknows-frontend
转换的方法在**src\common\wallet.ts**
在app.vue嵌套了provider
`src\views\home\Home.vue`这里使用了VueMissReact，也就是会造出页面刷新的bug所在。

`src/components/navigator/Navigator.vue`在这里使用了react的hooks转换出来的`useEthosForVue`，工作正常。

**Comment by devilwjp** [comment]
@e274426380 好的，我跑下看看

**Comment by devilwjp** [comment]
@e274426380 你的项目，我可以正常的跑
VueMiss包在container之外没有问题  
![image](https://user-images.githubusercontent.com/38802722/203733253-2945103c-6961-4fe2-8db5-e40aa940d82c.png)
![image](https://user-images.githubusercontent.com/38802722/203733343-22233494-2fa2-48e9-b83c-297b8ac9c62b.png)

**Comment by e274426380** [comment]
@devilwjp 这个时候可以正常跑，但是仔细看会发现页面隔几秒就会跳一下，控制台里的console可以看到问题。
应该是onMounted函数被反复触发的原因？我也不知道为什么会反复触发onMounted

**Comment by e274426380** [comment]
> @e274426380 两次onMounted确实是MissVue造成的，应该是个bug，但是影响不大

我这里的运行是只要停留在这个页面，就会一直反复触发组件里onMounted里的函数，不只有两次，而且会导致页面反复上跳到最顶部，很奇怪。

**Comment by devilwjp** [comment]
@e274426380 你可以删除node_modules，重新安装一下你的依赖，你的情况估计是哪个三方依赖出问题了

**Comment by devilwjp** [comment]
@e274426380 记得连你的lock文件也删除

**Comment by devilwjp** [comment]
@e274426380 你的问题我知道了
你不能在onMounted钩子里用hooks

**Comment by devilwjp** [comment]
@e274426380 不论是vue的规范还是react的规范，使用hooks都必须是明确的，不能在一个不明确的回调函数里使用，也不能在循环或者判断里使用hooks，要把hooks提到外面直接使用

**Comment by e274426380** [comment]
@devilwjp 感谢，我试

> @e274426380 不论是vue的规范还是react的规范，使用hooks都必须是明确的，不能在一个不明确的回调函数里使用，也不能在循环或者判断里使用hooks，要把hooks提到外面直接使用

学到了，但是只是单纯的不在onMounted里用hooks还是会出现这个问题，我清一下node_modules试一试

**Comment by e274426380** [comment]
@devilwjp 问题解决。
清理node_modules后重装再清理掉本地网页的缓存就正常了……也不知道是怎么触发出来的这个神奇bug，可能是项目移植的屎山代码

**Comment by devilwjp** [comment]
@e274426380 至于onMounted的问题，我会想办法修复，如果你对视图性能要求不是太高，可以先这么用，我会尽快解决这个问题

**Comment by e274426380** [comment]
@devilwjp 这个问题不重要，我对性能要求不高。感谢为我解答疑惑
