### ISSUE TITLE
转换成Vue的React Hooks里有个类似于心跳一样的功能会造成页面不断刷新怎么办？

### ISSUE THREAD

**Issue by e274426380** [devilwjp/veaury#49]
大佬你好，上次这个bug我找到了如何触发。
https://github.com/devilwjp/veaury/issues/48
将使用的这个钱包连接以后，依赖里的这个包有一个属性是`将contents每隔几秒更新一次，提供 有关已连接钱包内容的最新信息。`
https://docs.ethoswallet.xyz/hooks
我怀疑是这个每几秒更新的属性导致页面刷新的bug。
当钱包没有连接时不会触发这个bug，一旦连接就会出现问题

**Comment by devilwjp** [comment]
@e274426380 
嗯，现在只要套在VueMissReact里的所有组件，只要VueMissReact有更新，套在里面的组件就会重新mounted，你可以精细化的使用，不要套早最外层，哪里要使用你钱包数据了，就套在这个组件外层，这样避免不必要的刷新

**Comment by e274426380** [comment]
@devilwjp 确实是这样，我现在单独把导航条和VueMissReact组了个组件，现在只有导航条会mounted了，感谢大佬的帮助。
