### ISSUE TITLE
Elastic UI ‘Failed to fetch dynamically imported module’

### ISSUE THREAD

**Issue by AimSteyz** [devilwjp/veaury#5]
Hi,

when we try to display an icon of EuiIcon using veaury, we got this error
 
 `GET http://localhost:3000/node_modules/.vite/deps/assets/heart?import net::ERR_ABORTED 504 (Gateway Timeout)
 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://localhost:3000/node_modules/.vite/deps/assets/heart?import`
 
 Step to reproduce the error:

-  Install Eui `yarn add @elastic/eui @elastic/datemath @emotion/react moment prop-types`
- Import an EuiIcon and use the component 
`import React from 'react';`
`import { EuiIcon } from '@elastic/eui';`
`export default () => {`
`    return(`
`        <EuiIcon type="heart" />`
`    );`
`}`

**Comment by devilwjp** [comment]
@AimSteyz 
I think this problem may be because your project is built with vite, and I found that EuiIcon uses dynamic import, but vite does not support dynamic import, but luckily I found a solution in the documentation of @elastic/eui.  
[https://github.com/elastic/eui/blob/main/wiki/consuming.md#failing-icon-imports](https://github.com/elastic/eui/blob/main/wiki/consuming.md#failing-icon-imports)  

The following is an example of importing the heart icon in the vue3 file  
```vue
<script setup>
import { appendIconComponentCache } from '@elastic/eui/es/components/icon/icon';
import { icon as heart } from '@elastic/eui/es/components/icon/assets/heart';
import { EuiIcon } from '@elastic/eui';
import { applyReactInVue } from 'veaury'
appendIconComponentCache({
  heart
});
const EuiIconVue = applyReactInVue(EuiIcon)
</script>

<template>
  <EuiIconVue type="heart"/>
</template>
```

**Comment by AimSteyz** [comment]
It work flawlessly for component like that, but would you have an idea on how to do it with some component like "combo box"
https://elastic.github.io/eui/#/forms/combo-box (Second exemple, dont forget to import the css `import "@elastic/eui/dist/eui_theme_light.css"`)
When used it display this
![comp](https://user-images.githubusercontent.com/76852650/166654426-abd6e112-ba69-49ec-9cda-ea3e6b6a2a1e.png)

With this error
![err](https://user-images.githubusercontent.com/76852650/166654456-5f114404-7a66-470e-88a5-3cd6e3d83e60.png)

**Comment by devilwjp** [comment]
@AimSteyz 
This problem still seems to be a dynamic import problem, you still need to add `arrowDown` using `appendIconComponentCache` in advance .
```js
import { appendIconComponentCache } from '@elastic/eui/es/components/icon/icon';
import { icon as arrowDown } from '@elastic/eui/es/components/icon/assets/arraw_down';
appendIconComponentCache({
  arrowDown,
});
```

**Comment by AimSteyz** [comment]
I've try something similar but i might have done something wrong so it was not working
the imported icons are not centered but i may find why, probably a css problem, thank you 
![center](https://user-images.githubusercontent.com/76852650/166660166-691a34f7-67ab-4028-9463-9084146a830a.png)
!
