### ISSUE TITLE
Any plans to make it compatible with Vue4?

### ISSUE THREAD

**Issue by rouralberto** [devilwjp/veaury#51]
I tried to upgrade my project to Vue4 and veaury is the only package stopping the show. Is there any plans for it to make it work with Vue4?

**Comment by devilwjp** [comment]
@rouralberto 
As far as I know, the vue team has not released vue4, whether it is an alpha version or a beta version, or even a canary version.

**Comment by rouralberto** [comment]
Damn, sorry. You are right. I confused the Vite 4 with Vue 4 in the error message! I'll investigate how to make it work with Vite 4 first. Sorry!

**Comment by devilwjp** [comment]
@rouralberto 
Ok, I will build a vite4 project for debugging
