### ISSUE TITLE
In the react project built with vite, when importing jsx files, an error "Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension."

### ISSUE THREAD

**Issue by Suchben** [devilwjp/veaury#56]
With some examples?

**Comment by Suchben** [comment]
<img width="898" alt="image" src="https://user-images.githubusercontent.com/7865308/219935010-28586b44-7257-408a-853e-11aa3fb07e3e.png">

**Comment by Suchben** [comment]
[my-vue-app.zip](https://github.com/devilwjp/veaury/files/10776573/my-vue-app.zip)
我使用vite创建了一个项目，按照文档进行配置，但是报如下的错误，方便的时候您帮我看一下。感谢
<img width="933" alt="image" src="https://user-images.githubusercontent.com/7865308/219941528-fd2f1e65-8522-4432-8ce6-ed2a1392749c.png">

**Comment by devilwjp** [comment]
@Suchben 可以先把.jsx文件改成.tsx可以解决这个问题

**Comment by devilwjp** [comment]
@Suchben 这个问题会在最新的更新中解决

**Comment by devilwjp** [comment]
@Suchben 版本2.3.12已修复这个问题
