### ISSUE TITLE
applyPureReactInVue 引入 jsx 文件报错  Failed to parse source for import analysis because the content contains invalid JS syntax.

### ISSUE THREAD

**Issue by lqisa** [devilwjp/veaury#57]
<img width="832" alt="image" src="https://user-images.githubusercontent.com/9304478/220029674-6bfaa55d-3a8b-4668-b4c4-6d0d3e41d206.png">

直接引入 jsx 文件报错
修改配置文件 veaury/vite/index.js 内 esbuild 相关选项即可
<img width="402" alt="image" src="https://user-images.githubusercontent.com/9304478/220031321-26868aa5-c8f4-4069-a36d-d3c4b4f65624.png">

**Comment by devilwjp** [comment]
@lqisa 更新一下最新版，参考(#56)
