### ISSUE TITLE
在vue里用react组件样式没了怎么办

### ISSUE THREAD

**Issue by jinchetu** [devilwjp/veaury#58]

**Comment by devilwjp** [comment]
@jinchetu 引入样式啊

**Comment by jinchetu** [comment]
@devilwjp  在哪里引入  我在react组件里引入了
![image](https://user-images.githubusercontent.com/106373677/221527664-681346a6-2229-4c63-9bb4-7f6e02bead76.png)

**Comment by devilwjp** [comment]
@jinchetu 你可以看看这个css引到了吗？或者你css中的样式类是否符合
