### ISSUE TITLE
Elastic UI CSS missalignement

### ISSUE THREAD

**Issue by AimSteyz** [devilwjp/veaury#6]
Hi again,

So this is the follow of the #5 issue, the CSS cant align correctly, i've try modifying the CSS file "@elastic/eui/dist/eui_theme_light.css"
but it does'nt seems to work

Here is what I have 
![Vuer](https://user-images.githubusercontent.com/76852650/166919741-626b7a2b-ac85-42de-9214-70d467c73c58.png)

And the same component in React
![Reacter](https://user-images.githubusercontent.com/76852650/166919964-1f686ad2-b2e4-4789-b061-8d8842f3d6d7.png)

**Comment by devilwjp** [comment]
@AimSteyz 
I compared your two pictures, and I found that the font style and border style are different, which means that a basic style is missing.  

Is the React component displayed in another React project, or in a Vue project?

Because different projects have their own different basic styles.

And I also found that in the example of elastic_ui's combo-box, there is a public style with a button class, and this button class is not included in @elastic/eui/dist/eui_theme_light.css.

**Comment by AimSteyz** [comment]
The style are differents but it is the same CSS file imported for each
The screen is from the same component but in react so it the "same" things
![Screenshot from 2022-05-05 14-57-54](https://user-images.githubusercontent.com/76852650/166928008-cbde8948-e293-4f0c-a93c-e6f9e10d6acd.png)

But modifying the css in the vue project didnt impact the display even if it work when unclicking the box on your picture
![Screenshot from 2022-05-05 14-58-19](https://user-images.githubusercontent.com/76852650/166928029-ea5a7db3-e23a-4668-b7e7-24c32a59ca72.png)

**Comment by devilwjp** [comment]
@AimSteyz 
I mean, the reason why this icon cannot be centered is not the width attribute, but the default padding of the browser's button tag is 6px, you only need to set the padding and margin of the browser's default button to 0px, and it will be centered , such as the following example.  
```css
button {
    background: none;
    border: none;
    padding: 0px;
    margin: 0px;
    color: inherit;
    border-radius: 0px;
    font-size: inherit;
}
```

**Comment by AimSteyz** [comment]
Oh ok i understand sorry, but this is not a button that i create, this is a component from a lib, so this is not a button that i have create here is all my file to get this code :
![tmp](https://user-images.githubusercontent.com/76852650/166931136-d3d25828-362c-4bdc-9f65-98c5a9c2907e.png)

**Comment by devilwjp** [comment]
I think it may be that vue3's vite template project lacks style rewriting for button tags. You can try adding a style tag to this vue file and add the button style I provided above.

**Comment by AimSteyz** [comment]
Ok thank you

**Comment by devilwjp** [comment]
@AimSteyz 

Aha! I found the cause of the problem, you should use EuiProvider in the outermost layer.

```vue
<script setup>
import '@elastic/eui/dist/eui_theme_light.css';
import { ref } from 'vue';
import { appendIconComponentCache } from '@elastic/eui/es/components/icon/icon';
import { icon as arrowDown } from '@elastic/eui/es/components/icon/assets/arrow_down';
import { icon as returnKey } from '@elastic/eui/es/components/icon/assets/return_key';
import { EuiComboBox, EuiProvider } from '@elastic/eui';
import { applyReactInVue } from 'veaury'

const EuiProviderVue = applyReactInVue(EuiProvider)
const optionsStatic = ref([]);

appendIconComponentCache({
  arrowDown,
  returnKey
});
const EuiComboBoxVue = applyReactInVue(EuiComboBox)
</script>

<template>
  <EuiProviderVue colorMode="light">
    <EuiComboBoxVue
        aria-label="Accessible screen reader label"
        placeholder="Select or create options"
        :options="optionsStatic"
        :isClearable="true"
        data-test-subj="demoComboBox"
        :autoFocus="true"
    />
  </EuiProviderVue>
</template>
```

**Comment by AimSteyz** [comment]
> ```
> <script setup>
> import '@elastic/eui/dist/eui_theme_light.css';
> import { ref } from 'vue';
> import { appendIconComponentCache } from '@elastic/eui/es/components/icon/icon';
> import { icon as arrowDown } from '@elastic/eui/es/components/icon/assets/arrow_down';
> import { icon as returnKey } from '@elastic/eui/es/components/icon/assets/return_key';
> import { EuiComboBox, EuiProvider } from '@elastic/eui';
> import { applyReactInVue } from 'veaury'
> 
> const EuiProviderVue = applyReactInVue(EuiProvider)
> const optionsStatic = ref([]);
> 
> appendIconComponentCache({
>   arrowDown,
>   returnKey
> });
> const EuiComboBoxVue = applyReactInVue(EuiComboBox)
> </script>
> 
> <template>
>   <EuiProviderVue colorMode="light">
>     <EuiComboBoxVue
>         aria-label="Accessible screen reader label"
>         placeholder="Select or create options"
>         :options="optionsStatic"
>         :isClearable="true"
>         data-test-subj="demoComboBox"
>         :autoFocus="true"
>     />
>   </EuiProviderVue>
> </template>
> ```

Waho, thank you ! I close the issue, Thank you very much !
