### ISSUE TITLE
Compilation failed with webpack setup

### ISSUE THREAD

**Issue by manojditstek** [devilwjp/veaury#61]
I have clone the project with "dev-project-vue3" after that run the cmd 'npm i' getting package error. package alrady installed but still throwing error. please provide solutions 
![image](https://user-images.githubusercontent.com/92157610/223355804-3a75b47a-d66d-4fa1-a77a-046be7912f39.png)
![image](https://user-images.githubusercontent.com/92157610/223356033-5b1838ff-5e22-4e7b-a3cc-1420a5c1fa4a.png)

**Comment by devilwjp** [comment]
@manojditstek 
The project "dev-project-vue3" cannot be cloned alone. It is the development and debugging environment of veaury. In the alias of webpack, the dependency of veaury will be pointed to the src subdirectory of the upper directory, unless you pass an environment variable BUILD_TYPE=remote , will point to the veaury installed by npm, which has been explained in the second screenshot you provided.

![image](https://user-images.githubusercontent.com/38802722/223598301-5717a205-ef32-437a-903c-21d1b23cad48.png)

It is suggested that you can remove the point of veaury in alias.

**Comment by manojditstek** [comment]
@devilwjp Thanks for the explaination and suggestion.

If I configured with vite then project run and rendured react file but with webpack commented above line as you suggested, it's throwing error like this -
![image](https://user-images.githubusercontent.com/92157610/223655587-ad0902f4-4abb-402d-ab72-48ceec16d364.png)

//Chat.jsx
`export default function () {
    return (<div>Hello</div>);
  }`

**Comment by devilwjp** [comment]
@manojditstek 
This error comes from chat.jsx, because React is not imported in the file. Because your project is a vue project, some babel presets of react are not configured, so react will not be imported automatically, you need to import it manually in chat.jsx.
For example, add a line of code at the top of the chat.jsx file.
```jsx
import React from 'react';
```

**Comment by manojditstek** [comment]
@devilwjp 
Now it's working. Thanks for the help :)
