### ISSUE TITLE
大佬，vue项目中使用react组件，对table组件的cell函数 怎么处理

### ISSUE THREAD

**Issue by xiaobc1234** [devilwjp/veaury#63]
table组件有个columns的属性，react格式如下：

```JSON
[{
  title: '姓名',
  dataIndex: 'name',
  cell: (value, index, record) =>  {
    return <div>{value}</div>
  }
}]

```

我现在是直接下面这么传（三种方式都报错）
![image](https://user-images.githubusercontent.com/4045741/224948506-854a8818-01a8-49c8-8e82-a49c9fe9d60e.png)

报错信息如下:
![image](https://user-images.githubusercontent.com/4045741/224948676-c833f316-ffa0-4061-9c6a-87b3390eacb6.png)

**Comment by devilwjp** [comment]
@xiaobc1234 
使用getReactNode， https://github.com/devilwjp/veaury#usage-of-getreactnode

**Comment by xiaobc1234** [comment]
> @xiaobc1234 使用getReactNode， https://github.com/devilwjp/veaury#usage-of-getreactnode

vue文件里这么使用，会报下面的错
![image](https://user-images.githubusercontent.com/4045741/224956383-37ae3b6b-ae60-4b67-a8dd-f9b4360780cf.png)

![image](https://user-images.githubusercontent.com/4045741/224956448-f8a20bfa-7238-48f5-85d3-47f40e7f762b.png)

**Comment by devilwjp** [comment]
@xiaobc1234 完整vue的代码贴出来

**Comment by xiaobc1234** [comment]
> @xiaobc1234 你这个错是vue文件不支持jsx，你看看你的<script>部分是怎么声明的

我加了  lang="jsx", 然后我发现直接返回数字或者字符串 也会报  TypeError: Illegal invocation 的错误
![image](https://user-images.githubusercontent.com/4045741/224958668-f1b54863-0d58-4174-a344-7f54ef12a7ec.png)

![image](https://user-images.githubusercontent.com/4045741/224960804-cca8bab7-17fc-403b-9a1a-f34d561fada4.png)

**Comment by devilwjp** [comment]
@xiaobc1234 完整的代码贴出来，现在你的截图无法给你排查问题

**Comment by xiaobc1234** [comment]
> @xiaobc1234 完整的代码贴出来，现在你的截图无法给你排查问题

我单独做了一个简单demo 没问题，我发现是我组件使用有问题，参数格式传错了
![image](https://user-images.githubusercontent.com/4045741/224967912-98f6e8d5-9f20-4dbc-bfe4-26b70221f5e6.png)

改成下面就好了
![image](https://user-images.githubusercontent.com/4045741/224968027-6cc3e2a7-d4b5-42a2-9904-a0172b147c33.png)
