### ISSUE TITLE
在vue使用react组件， 传参响应很慢

### ISSUE THREAD

**Issue by xinre** [devilwjp/veaury#66]
useEffect(() => {
    updateTabsBounds(false);
    containerRef.current.scrollLeft = containerRef.current.scrollWidth;
    window.addEventListener('resize', onResize);
    window.observerTab = (config) => {
      console.log(config, "configconfigconfig");
      const findIndex = list.findIndex((element) => element.id === config.name);
      if (findIndex === -1) {
        list.push(new ITab({ active: true, pinned: null, favicon: config.favicon, title: config.pluginName, closable: true, content: config }, config.name));
        setList(list.concat([]));
      }
      setSelectKey(config.name)
    }
  }, [list])

observerTab在vue中调用 config 返回的很慢

**Comment by xinre** [comment]
还有在react组件中获取vue那边传过来的函数中的参数的时候也会卡一会有值进来， 请问这个应该怎么处理啊，

**Comment by devilwjp** [comment]
@xinre 提供完整的复现问题的例子给我吧，我来复现一下

**Comment by xinre** [comment]
抱歉， 我解决了， 应该是我这边的问题。 当时只是打印慢了一点。
