### ISSUE TITLE
vue中使用react组件，dom上多了一层div，导致样式 和 react项目中效果不一致的问题，有什么好的解决方法吗

### ISSUE THREAD

**Issue by xiaobc1234** [devilwjp/veaury#68]
vue项目中效果
![image](https://user-images.githubusercontent.com/4045741/229678460-4db78667-ada3-4179-b42e-9eeeb0a98133.png)

React项目中效果
![image](https://user-images.githubusercontent.com/4045741/229678733-48110c07-549d-4f2d-bba7-6fb44666a528.png)

**Comment by xiaobc1234** [comment]
暂时只能单独设置样式覆盖了
```

 & > div[__use_react_component_wrap] {
      flex: 4 !important;
      width: 80% !important;
      max-width: 400px !important;
      margin: 0 auto !important;
    }


```

**Comment by devilwjp** [comment]
使用`applyPureReactInVue`
