### ISSUE TITLE
Vue3组件如何获取子React组件的动态值

### ISSUE THREAD

**Issue by itmanyong** [devilwjp/veaury#7]
version:
react-18.1.0
react-dom-18.1.0
vue-3.2.25
veaury-1.0.5
example:
react子组件内部有一计数状态并通过ref返回
`const [count,setcount] = useState(6);`
`useImperativeHandle(ref,()=>({count,setcount}),[count])`
vue3父组件接收并显示/控制：
`const reactCountRef = ref(null);`
`const ccc = computed(()=>reactCountRef?.value?.reactRef?.count || null)`

当调用reactCountRef.value.setcount的时候，
1.reactCountRef.value.count只会变化一次，但不响应界面，watchEffect不生效
2.reactCountRef.value.reactRef.count会同步变化值，但不响应界面，watchEffect不生效
??如何才能动态响应，例如：vue父组件显示count的实时值,包括watchEffect生效

**Comment by devilwjp** [comment]
@itmanyong 等我晚上复现一下这个场景，再给你答复

**Comment by devilwjp** [comment]
@itmanyong 
先让我理解一下你表达的含义：  
1. react作为子组件，该组件维护了一个状态count，并且该组件通过useImperativeHandle钩子把count和setCount抛给父组件  
2. 父组件我们先不考虑vue组件，即便父组件是react组件，其实也无法直接监听子组件抛出的属性变化，这是react的设计如此  
3. 因此当把父组件换成vue组件，也无法做到监听react子组件的count  
4. 在react的设计中，需要父组件主动传入子组件一个事件或者方法，由子组件触发这个事件或者方法来通知父组件，或者维护一个自定义的hooks，内部使用context解决父子组件共用一个状态的设计   
5. 即便是vue的设计中，也无法在父组件监听子组件抛出的状态

**Comment by itmanyong** [comment]
> @itmanyong 先让我理解一下你表达的含义：
> 
> 1. react作为子组件，该组件维护了一个状态count，并且该组件通过useImperativeHandle钩子把count和setCount抛给父组件
> 2. 父组件我们先不考虑vue组件，即便父组件是react组件，其实也无法直接监听子组件抛出的属性变化，这是react的设计如此
> 3. 因此当把父组件换成vue组件，也无法做到监听react子组件的count
> 4. 在react的设计中，需要父组件主动传入子组件一个事件或者方法，由子组件触发这个事件或者方法来通知父组件，或者维护一个自定义的hooks，内部使用context解决父子组件共用一个状态的设计
> 5. 即便是vue的设计中，也无法在父组件直接监听子组件内部自己维护的状态，仍然应该使用事件或者provide/inject完成

仔细想来也确实如此，只是觉的传递事件/provide的方式不够优雅或小题大做感觉。还有一个小的tips，react18下会有createRoot API版本错误提示，可以兼容下，

**Comment by devilwjp** [comment]
@itmanyong 关于React18的问题，确实在兼容中，因为该库其实是基于react17或者更低版本开发的，没想到17的寿命如此的端，而18又有了一些破坏性的api升级，计划会在本周兼容掉

**Comment by hyzx86** [comment]
我用 函数作为 参数 从 vue 传递到 react组件里的

见：
https://github.com/devilwjp/veaury/issues/8
