### ISSUE TITLE
Vue项目中调用React组件

### ISSUE THREAD

**Issue by probe-pg** [devilwjp/veaury#70]
场景是在dialog中，调用React组件，销毁dialog不成功，遇到的报错，有手动释放React方法吗？

![1680744370529](https://user-images.githubusercontent.com/44151982/230249500-9fb926f7-3e66-470f-84a8-54b612308fe1.jpg)

**Comment by devilwjp** [comment]
@probe-pg 提供一个可以复现问题的例子

**Comment by probe-pg** [comment]
已经解决，不是框架问题，多谢
