### ISSUE TITLE
Vite打包 ReferenceError: require is not defined

### ISSUE THREAD

**Issue by probe-pg** [devilwjp/veaury#71]
veaury: 2.3.12,  降到 2.3.1 和2.3.8 都试了 都不行

![Snipaste_2023-04-06_12-27-27](https://user-images.githubusercontent.com/44151982/230272155-2c9e6567-0f9b-40f5-b8ec-12b00164ef9a.png)

**Comment by devilwjp** [comment]
@probe-pg 这个报错和veaury无关，是你项目的三方依赖中使用了require

**Comment by probe-pg** [comment]
确实是 其他第三库问题，添加
commonjsOptions: {
        transformMixedEsModules: true
      },
就好使了，谢谢
