### ISSUE TITLE
在vue项目中加载react组件后，会经常报错：caught RangeError: Maximum call stack size exceeded  

### ISSUE THREAD

**Issue by citynook** [devilwjp/veaury#73]
veaury: 2.3.12
amis-editor: 5.2.5

在vue中使用applyPureReactInVue能正常加载amis-edito编辑器，但在编辑器操作过程中，会经常报下面的错误，此时编辑器无法正常操作，必须刷新页面后才能再次正常，然后操作一会儿就又会报错。
![image](https://user-images.githubusercontent.com/127393297/231326999-7a823ba1-b343-4b19-828e-47a3968d77b1.png)

代码：

<template>
  <div class="amis">
    <amisEditor
      className="is-fixed"
      :isMobile="isMobile"
      :preview="isPreview"
      :theme="theme"
      :amisEnv="env"
      :value="schema"
      :onChange="onChange"
      :onSave="onSave"
      :showCustomRenderersPanel="true"
      :plugins="plusins"
      :actionOptions="{ showOldEntry: false }"
    />
  </div>
</template>
<script>
  import { alert, confirm } from 'amis';
  import { Editor } from 'amis-editor';
  import { applyPureReactInVue } from 'veaury';
  import { defHttp } from '/@/utils/http/axios';
  import { RequestEnum } from '/@/enums/httpEnum';
  import { useMessage } from '/@/hooks/web/useMessage';
  import '@fortawesome/fontawesome-free/css/all.css';
  import '@fortawesome/fontawesome-free/css/v4-shims.css';
  import 'amis/lib/themes/default.css';
  import 'amis/lib/helper.css';
  import 'amis/sdk/iconfont.css';
  import '../../../../node_modules/amis-editor-core/lib/style.css';
  import LayoutList from './layout/index';

  const { createMessage } = useMessage();
  const defaultSchema = {
    type: 'page',
    title: '新页面',
    body: [],
    id: 'u:3303380d1b8c',
    asideResizor: false,
    style: {
      boxShadow: ' 0px 0px 0px 0px transparent',
    },
    pullRefresh: {
      disabled: true,
    },
    regions: ['body', 'toolbar', 'header', 'aside'],
  };
  export default {
    // eslint-disable-next-line vue/multi-word-component-names
    name: 'Editor',
    components: {
      amisEditor: applyPureReactInVue(Editor),
    },
    props: {
      isPreview: {
        type: Boolean,
        default: false,
      },
      isMobile: {
        type: Boolean,
        default: false,
      },
      theme: {
        type: String,
        default: 'cxd',
      },
    },
    data() {
      return {
        schema: defaultSchema,
        plusins: LayoutList,
        actionOptions: {
          showOldEntry: false,
        },
        env: {
          fetcher: (config) => {
            console.log('AmisEditor Request: ', config.method, config.url, config.data, config);
            if (this.isPreview == true || config.method?.toUpperCase() === RequestEnum.GET) {
              return defHttp.request(config, { isReturnNativeResponse: true });
            }
          },
          isCancel: (e) => axios.isCancel(e),
          alert,
          notify: (type, msg) => {
            //toast[type] ? toast[type](msg, type === 'error' ? '系统错误' : '系统消息') : console.warn('[Notify]', type, msg);
            //console.log('[notify]', type, msg);
            if (type == 'error') {
              createMessage.error(msg);
            } else if (type == 'success') {
              createMessage.success(msg);
            } else if (type == 'warn' || type == 'warning') {
              createMessage.warning(msg);
            } else {
              createMessage.info(msg);
            }
          },
          confirm,
          copy: (contents, options = {}) => {
            const ret = copy(contents, options);
            //ret && (!options || options.shutup !== true) && toast.info('内容已拷贝到剪切板');
            ret && createMessage.info('内容已拷贝到剪切板');
            return ret;
          },
        },
      };
    },
    mounted() {
      this.schema = this.value;
    },
    methods: {
      setSchema(data) {
        if (data == null || data == undefined) {
          this.schema = defaultSchema;
        } else {
          this.schema = Object.prototype.toString.call(data) === '[object String]' ? JSON.parse(data) : data;
        }
      },

      getSchema() {
        return this.schema;
      },

      onChange(e) {
        this.schema = e;
        // eslint-disable-next-line vue/require-explicit-emits
        this.$emit('onChange', e);
      },
      onSave() {},
    },
  };
</script>

<style lang="less" scoped>
  .amis {
    width: 100%;
    height: calc(100vh - 60px * 2.7) !important;

    #editor {
      width: 100%;
      height: calc(100vh - 60px * 2.7) !important;
    }
  }

  .ae-Editor .ae-Editor-inner {
    height: calc(100vh - 60px * 2.7) !important;
  }
</style>

**Comment by devilwjp** [comment]
@citynook 请提供一个完整可以复现问题的demo项目

**Comment by citynook** [comment]
有邮箱吗，我可以打包发给你。

**Comment by devilwjp** [comment]
@citynook 建议直接在github上提交demo项目，我去fork

**Comment by citynook** [comment]
好的，我试一下~

**Comment by citynook** [comment]
项目建好了，错误可以复现，但公司内网无法上传源码~~方便的话能给个QQ邮箱吗？

**Comment by devilwjp** [comment]
@devilwjp 9700616@qq.com

**Comment by citynook** [comment]
邮件已发送，请查收！

**Comment by citynook** [comment]
请问demo是否能够复现问题？是否需要提供其它的资料？在AmisEditor编辑器中操作时产生的错误，是否可以解决？
若无法解决，就只能忍痛在 Vue 项目中放弃 AmisEditor了，只能找一个 React 项目使用。
我正在试用JeecgBoot，功能很全，但前端是 Vue，想将 AmisEditor 集成进来，尝试低代码开发。
请问除了 Ant Design Pro 之外，能否介绍几个开箱即用的 React 前端中台开源项目，如果有配套的后端微服务项目更佳。
多谢！

**Comment by devilwjp** [comment]
@citynook 抱歉你的demo我还没有看，最近一段时间比较忙，我本周会抽空看一下

**Comment by citynook** [comment]
客气了，我这边不急，就是找一些开箱即用的项目在试用，可惜找不到太多 React 的，都是 Vue 偏多，所以才需要在 Vue 中使用 React 控件。要是能找到一个不错的 React 前端项目，和 AmisEditor 集成就容易多了。

那就先不打扰了，等你的回复~

**Comment by devilwjp** [comment]
@zhangHongEn 麻烦协助看一下

**Comment by zhangHongEn** [comment]
可以分批排查代码、增加打印查找何处出现了循环引用的对象

**Comment by citynook** [comment]
@zhangHongEn 这个AmisEditor是百度的页面编辑器，官方的react项目运行后，按同样的操作步骤不会发生问题。

在使用此插件在vue内导入AmisEditor react控件时，才会发生这类问题。

我无法判断是AmisEditor的问题，还是这个插件的问题，但比较倾向此插件在导入react控件后，可能有些事件无法完全处理，导致发生错误。

我以前是做后端的，才接触Vue和React不到一个月的时间，所以也不会深入调试前端项目。如果这个问题无法解决，或许只能考虑使用React前端项目，避免在Vue中使用。

多谢！

**Comment by citynook** [comment]
@zhangHongEn @devilwjp AmisEditor发布了新版本，我再测试一段时间，看新版本是否还会发生类似的问题，再和两位分享下测试结果。

**Comment by zhangHongEn** [comment]
> @zhangHongEn 这个AmisEditor是百度的页面编辑器，官方的react项目运行后，按同样的操作步骤不会发生问题。
> 
> 在使用此插件在vue内导入AmisEditor react控件时，才会发生这类问题。
> 
> 我无法判断是AmisEditor的问题，还是这个插件的问题，但比较倾向此插件在导入react控件后，可能有些事件无法完全处理，导致发生错误。
> 
> 我以前是做后端的，才接触Vue和React不到一个月的时间，所以也不会深入调试前端项目。如果这个问题无法解决，或许只能考虑使用React前端项目，避免在Vue中使用。
> 
> 多谢！

@citynook 我没办法复现问题, 我启动加了很多组件都无法出现错误, 如果你有复现规律也可以告诉我

**Comment by citynook** [comment]
@zhangHongEn 项目的readme.md中有复现的步骤，我这里粘贴下：

本地环境：
vscode: 1.77.1
nodejs: 18.15.0

错误复现步骤：
1. 复制 test.json 的内容
2. 在 Amis 编辑器中，进入左侧面板的【代码】窗口，将复制的 json 内容粘贴到窗口中，然后编辑器会重新渲染。
3. 选中表格控件的【操作】列中的【查看】按钮，点击 右侧面板 -> 事件 -> 配置动作(旧版)按钮，进入【动作】对话框。
4. 点击【配置弹框内容】按钮，进入【配置弹框内容】窗口。
5. 进入 左侧面板 -> 【代码】窗口，复制所有的 json 代码。
6. 退出对话框，回到编辑器主界面。
7. 选中表格控件的【操作】列中的【删除】按钮，点击 右侧面板 -> 事件 -> 工具框中的【+】按钮，进入【动作配置】对话框。
8. 执行动作选择：打开弹窗，然后点击右侧的【去配置】按钮，进入【配置弹框内容】界面。
9. 打开左侧面板  -> 【代码】窗口，粘贴第 5 步复制的 json，替代原有的 json。
10.点击两次【确认】按钮，当回到编辑器主窗口时，chrome 的控制台就会显示错误，编辑器的左侧面板也无法正常渲染，可参见错误信息的截图：test.png

按上述步骤重复验证多次，每次都可以复现同样的错误。
用nodejs 17+版本也是相同的错误。

**Comment by citynook** [comment]
@zhangHongEn 第2-4这个步骤，也可以在点击“查看”按钮后，在浮动工具条中点击【配置弹框按钮】进入，其它操作步骤不变。

我刚在本地用上述步骤可以重现错误。

**Comment by zhangHongEn** [comment]
@citynook 我昨天按照步骤也重现了, 最近也很忙, 抱歉要晚点看

**Comment by citynook** [comment]
@zhangHongEn 客气客气，要谢谢你才对，工作之余还要额外花时间处理问题，辛苦了~~

**Comment by devilwjp** [comment]
@citynook 既然能复现，这个问题我会继续跟

**Comment by citynook** [comment]
@devilwjp 感谢~~

**Comment by citynook** [comment]
@zhangHongEn 请问有新的进展可以分享下吗~

**Comment by zhangHongEn** [comment]
> @zhangHongEn 请问有新的进展可以分享下吗~

抱歉久等了, 根据demo排查出问题, 是schema中有循环引用的属性导致渲染死循环, 需做如下改动:
``` js
// App.vue
import {shallowReactive} from "vue"
export default {
  setup(props) {  
    return {
      // shallowReactive浅相应, 不监听深层的循环引用的属性
      schema: shallowReactive(defaultSchema)
    }
  },
}
```

**Comment by citynook** [comment]
@zhangHongEn 我在发给 @devilwjp 的demo项目中按上面的方法改动，还是会报同样的错误，代码和报错截图如下。烦请有空的时候帮看一下是什么原因。第二张截图最下方的系统时间是今天中午近12点。

![image](https://github.com/devilwjp/veaury/assets/127393297/f8324899-9ed4-429a-b9d8-a0f4ea99d6b5)

![image](https://github.com/devilwjp/veaury/assets/127393297/1a921d30-26e4-416a-a3ef-4b0ae8ab0126)

**Comment by zhangHongEn** [comment]
@citynook 在setup中而不是data中使用shallowReactive

**Comment by ksmarsh** [comment]
你好 ，我这也有同样的问题，但我这没有使用vue3 的变量属性，所有变量都在react组件里，外部只引用react组件，仍然堆栈溢出，react组件内是 antv/graphin组件。只要注释掉graphin组件就不会报错。请问我该如何排查是什么变量导致的堆栈溢出。

**Comment by zhangHongEn** [comment]
@ksmarsh 麻烦提供错误信息和一份最小可复现demo吧

**Comment by ksmarsh** [comment]
[test (1).zip](https://github.com/devilwjp/veaury/files/12596386/test.1.zip)
这是demo 需要用yarn 安装依赖运行，运行后点击跳转进入拓扑图，再跳转回去后会报错。

**Comment by ksmarsh** [comment]
你好，请问这个问题有进展了吗

**Comment by zhangHongEn** [comment]
> 你好，请问这个问题有进展了吗

@ksmarsh  今天会看, 用法没问题, 可能是bug

**Comment by zhangHongEn** [comment]
@ksmarsh 已修复, 等发新版

**Comment by ksmarsh** [comment]
谢谢你的回复
