### ISSUE TITLE
vite的React项目里要用Vue组件,能正常跑起来，但是打包就报错，vue2、vue3都试过，一样的结果

### ISSUE THREAD

**Issue by nicky132** [devilwjp/veaury#74]
vite的React项目里要用Vue组件,能正常跑起来，但是打包就报错，vue2、vue3都试过，一样的结果。
问题复现demo的话我已发给过两位贡献者的其中一人了。
希望能快速解决一下。谢谢
@zhangHongEn @devilwjp

**Comment by devilwjp** [comment]
@nicky132 已单独和你沟通，并且已处理

**Comment by nicky132** [comment]
> @nicky132 已单独和你沟通，并且已处理

嗯，zhangHongEn大佬，通过把vue2和vue3排除ts类型检查来解决的，感谢大佬
