### ISSUE TITLE
怎样在React项目中引入vue3的tsx组件呢？

### ISSUE THREAD

**Issue by johnlin0207** [devilwjp/veaury#75]
首先applyPureReactInVue 或 applyVueInReact这两个包装方法不能用，按照这里的说明修改了包还是不行(https://github.com/devilwjp/veaury/blob/master/README_zhcn.md#vue-%E5%92%8C-react%E5%85%B1%E5%AD%98%E6%97%B6%E4%BC%9A%E5%BC%95%E5%8F%91jsx%E7%9A%84ts%E7%B1%BB%E5%9E%8B%E9%94%99%E8%AF%AF) 页面报错runtime-dom.esm-bundler.js:35  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'parentNode')

**Comment by devilwjp** [comment]
@johnlin0207 你可以提供一个可以复现你问题的项目，我根据你的项目的提供一个patch

**Comment by johnlin0207** [comment]
回复好快哈哈哈，这个demo麻烦你看看 https://github.com/johnlin0207/vite-react-ts/tree/react-vue3tsx

**Comment by johnlin0207** [comment]
> 回复好快哈哈哈，这个demo麻烦你看看 https://github.com/johnlin0207/vite-react-ts/tree/react-vue3tsx

启动后在http://localhost:5173/datamana/menu1复现，对应文件是/src/views/module1/menu1.tsx，引用的vue文件是/src/views/module1/Basic.tsx

**Comment by devilwjp** [comment]
@johnlin0207 你的项目并没有发现使用vue组件，也没有Basic.tsx
![image](https://user-images.githubusercontent.com/38802722/233928992-1953d2be-1ff8-46f1-b874-ea8a73cc7ab1.png)

**Comment by johnlin0207** [comment]
> @johnlin0207 你的项目并没有发现使用vue组件，也没有Basic.tsx ![image](https://user-images.githubusercontent.com/38802722/233928992-1953d2be-1ff8-46f1-b874-ea8a73cc7ab1.png)

https://github.com/johnlin0207/vite-react-ts/blob/react-vue3tsx/src/views/module1/Basic.tsx

**Comment by johnlin0207** [comment]
分支不对吧，是这个react-vue3tsx

**Comment by devilwjp** [comment]
@johnlin0207 
你的问题不是修改typescript声明的问题，而是你把vue的tsx文件和react的放在一起了，vue的tsx文件只能放在vue_app目录里，改成如下的结构就好了
![image](https://user-images.githubusercontent.com/38802722/233938991-0bb878ce-7664-43bc-834d-10478815f852.png)
![image](https://user-images.githubusercontent.com/38802722/233939114-7c21eb31-58b9-4025-986a-2ffa73d2695e.png)

**Comment by devilwjp** [comment]
@johnlin0207 
veauryVitePlugin，type为react时，模式设置是会识别vue_app目录下的tsx文件中的jsx以及vue文件内部的jsx编译成vue的jsx类型，其他的编译成react的jsx类型

**Comment by johnlin0207** [comment]
> @johnlin0207 你的问题不是修改typescript声明的问题，而是你把vue的tsx文件和react的放在一起了，vue的tsx文件只能放在vue_app目录里，改成如下的结构就好了 ![image](https://user-images.githubusercontent.com/38802722/233938991-0bb878ce-7664-43bc-834d-10478815f852.png) ![image](https://user-images.githubusercontent.com/38802722/233939114-7c21eb31-58b9-4025-986a-2ffa73d2695e.png)

好的。
文档里是：所有.vue文件以及在名为vue_app目录里的文件都将以vue jsx编译
===============
我以为.tsx的vue文件不需要呢
