### ISSUE TITLE
可以在react项目里的vue组件里使用vuex或者pinia吗，反之呢？

### ISSUE THREAD

**Issue by johnlin0207** [devilwjp/veaury#76]
或者能在vue组件中使用redux吗？不同框架组件之间的数据如何共享呢

**Comment by johnlin0207** [comment]
一个项目里vue和react组件可以完全自由相互引用吗，就如同同一个框架的项目？如果不是的话，支持到什么程度呢？

**Comment by devilwjp** [comment]
@johnlin0207 可以详细看下文档，都支持的

**Comment by devilwjp** [comment]
@johnlin0207 CrossingProvider只是其中的一种方式，即便没有veaury，在react中依然可以使用vuex，在vue中依然可以使用redux，状态管理插件本来就不依赖技术栈
