### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by lxychinese** [devilwjp/veaury#77]
dev-project-vue3这个工程   稳定出现 以下报错
Syntax Error: TypeError: Cannot read properties of null (reading 'content')

 @ ./src/pages/pureReactInVue/index.vue?vue&type=script&setup=true&lang=js 1:0-299 1:0-299 1:300-588 1:300-588
 @ ./src/pages/pureReactInVue/index.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js (webpack)-dev-server/client?http://10.15.164.224:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by xiaobc1234** [comment]
今天下午 vue 3.3.3的版本有问题，升级到 vue3.3.4 看行不行

**Comment by lxychinese** [comment]
vue3.3.4也不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月18日(星期四) 晚上8:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [devilwjp/veaury] 启动报错 (Issue #77)





 
今天下午 vue 3.3.3的版本有问题，升级到 vue3.3.4 看行不行

**Comment by devilwjp** [comment]
@lxychinese dev-project-vue3这个项目不能单独运行，必须是veaury整个项目一起运行
