### ISSUE TITLE
Can we modify / use plugins in the Vue app loaded for Vue in React usage?

### ISSUE THREAD

**Issue by Sidnioulz** [devilwjp/veaury#80]
First of all, congrats on making this fantastic package!

I'm trying to load Vue components in a React JSX context, but they require that a Vue plugin has been loaded beforehand into the Vue app instance. I'm curious if there's a way for me to pass options to the Vue app instance or to customise how it gets created initially.

**Comment by devilwjp** [comment]
@Sidnioulz 
Please refer to https://github.com/devilwjp/veaury/issues/60

**Comment by Sidnioulz** [comment]
Thank you :pray: I forgot to search closed issues too.
