### ISSUE TITLE
 Cannot read properties of undefined (reading '__esModule')

### ISSUE THREAD

**Issue by HandsomeBrother** [devilwjp/veaury#83]
<img width="927" alt="image" src="https://github.com/devilwjp/veaury/assets/20573564/63959d35-6581-499e-858e-1368abf85f27">
用webpack编译出来的文件，引入后报错Cannot read properties of undefined (reading '__esModule')

通过tsc编译的正常

**Comment by devilwjp** [comment]
@HandsomeBrother 提供一个测试项目给我

**Comment by HandsomeBrother** [comment]
https://github.com/HandsomeBrother/veaury-demo

**Comment by HandsomeBrother** [comment]
@devilwjp

**Comment by devilwjp** [comment]
@zhangHongEn 你也可以帮忙看下，我比较忙

**Comment by HandsomeBrother** [comment]
@devilwjp 这个项目里没有用，会在另一个项目里通过veaury引用这个react组件
<img width="484" alt="image" src="https://github.com/devilwjp/veaury/assets/20573564/2e0ee043-0aef-4b8c-ab35-b1a184f42681">

**Comment by zhangHongEn** [comment]
> @devilwjp 这个项目里没有用，会在另一个项目里通过veaury引用这个react组件 <img alt="image" width="484" src="https://user-images.githubusercontent.com/20573564/254199639-2e0ee043-0aef-4b8c-ab35-b1a184f42681.png">

console一下 StatPanel

**Comment by HandsomeBrother** [comment]
<img width="891" alt="image" src="https://github.com/devilwjp/veaury/assets/20573564/bce95777-99d6-455a-b5ae-df2aa18ccc46">
没到console, 加载的时候就报错了，会不会和esm有关，需要webpack打包成esm格式吗

**Comment by HandsomeBrother** [comment]
@zhangHongEn

**Comment by devilwjp** [comment]
@HandsomeBrother 他让你使用console打印是因为想知道StatPanel是不是undefined

**Comment by HandsomeBrother** [comment]
<img width="458" alt="image" src="https://github.com/devilwjp/veaury/assets/20573564/af265bfb-0f78-430f-b8a0-45ec3dbe03a3">
<img width="754" alt="image" src="https://github.com/devilwjp/veaury/assets/20573564/7ffb416d-3f81-4964-9e81-8fe6d813968a">
是的，undefined

**Comment by devilwjp** [comment]
@HandsomeBrother 所以这个是你自己的问题，不是veaury的问题，你传了一个undefined给veaury

**Comment by HandsomeBrother** [comment]
好的，谢谢
