### ISSUE TITLE
vue3使用npm安装的arco-design ui库 无法引入样式文件

### ISSUE THREAD

**Issue by xiaoli-style** [devilwjp/veaury#84]
import { createApp } from 'vue'
import App from './App.vue'

import '@arco-design/mobile-react/esm/style'
const app = createApp(App)
app.mount('#app')

控制台报错：
@pxtorem: ~pxtorem = function(value) {
                  ^
Inline JavaScript is not enabled. Is it set in your options?
      Error in F:\PhpstormProjects\react-vue\node_modules\@arco-design\mobile-react\tokens\mixin\pxtorem.less (line 3, column 10)
 @ ./node_modules/@arco-design/mobile-react/esm/transition/style/index.less 4:14-233 15:3-20:5 16:22-241
 @ ./node_modules/@arco-design/mobile-react/esm/transition/style/index.js 2:0-22
 @ ./node_modules/@arco-design/mobile-react/esm/style.js 58:0-28
 @ ./src/main.js 3:0-45

**Comment by devilwjp** [comment]
@xiaoli-style 你这个错误应该是sass-loader或者less-loader的版本不对

**Comment by huangkaoya** [comment]
这个问题还有后续么

**Comment by xiaoli-style** [comment]
> 这个问题还有后续么

没有后续了，这个ui库不支持vue，是react用的。并且官网未开发vue版本的mobile库，还是用vant吧
