### ISSUE TITLE
vue中使用react hooks组件需要什么配置吗，直接使用applyPureReactInVue报错了

### ISSUE THREAD

**Issue by HandsomeBrother** [devilwjp/veaury#86]
vue中使用react hooks组件需要什么配置吗，直接使用applyPureReactInVue报错了
<img width="1229" alt="image" src="https://github.com/devilwjp/veaury/assets/20573564/2994f18e-c119-48a6-9a07-c4d681df2a7e">

代码
```
// react
import React, {  useState } from 'react';
 export function PieChartPanel(props: any) {
  const [width, setWidth] = useState(0)
  setWidth(100)
  console.log('pie props', props, width)
  return (
    <div>demo</div>
  );
}

// use in vue

  import { applyPureReactInVue } from 'veaury'
  const PieChartVue = applyPureReactInVue(PieChartPanel)
  console.log('props.plugin.panel',  PieChartPanel)
```
<img width="1029" alt="image" src="https://github.com/devilwjp/veaury/assets/20573564/864210d1-d51d-442a-8ed3-e097af8c95b9">

**Comment by devilwjp** [comment]
@HandsomeBrother 请提供一个可以复现问题的项目

**Comment by HandsomeBrother** [comment]
@devilwjp https://github.com/HandsomeBrother/veaury-demo
1: npm i
2: npm run build
3: cd hello-world
4: npm i
5: npm run serve
6: open console

**Comment by devilwjp** [comment]
@HandsomeBrother 
![image](https://github.com/devilwjp/veaury/assets/38802722/80e495eb-f9ea-409e-9017-1266b99a14ba)
你的项目我跑过了，你的react组件把整个react的包也打进去了，然后引入vue项目时，veaury又引了react，产生了react多例，就会出现这个警告
正确的做法，react组件打包之后，不应该把react也打进去

**Comment by HandsomeBrother** [comment]
感谢，我完善了一下demo，通过npm包提取veaury apply方法场景的webpack相关配置，https://github.com/HandsomeBrother/veaury-demo可供参考
