### ISSUE TITLE
你好，在这个项目中引用veaury2.3.12运行报错，请问能帮忙解决下吗谢谢

### ISSUE THREAD

**Issue by jimoguilai** [devilwjp/veaury#87]
项目代码：https://gitee.com/dxz-open/vue-next-admin
在/src/views/lowercode/amis/ 下想试试vue3中引用react组件，但是vite中加了
`// type设为vue时, 所有名为react_app目录中的文件的jsx将被react jsx编译，其他文件里的jsx将以vue jsx编译
			veauryVitePlugins({
				type: 'vue'
			})`
启动就会报错，注释掉又能正常运行，请帮忙解决下谢谢

**Comment by devilwjp** [comment]
@jimoguilai 
你仓库里哪个分支？

**Comment by jimoguilai** [comment]
@devilwjp 大佬不行哦，就master分支的代码，我在vite.config.ts就这么配置的

**Comment by zhangHongEn** [comment]
@jimoguilai 修改react_app/Basic.js为Basic.jsx后缀

**Comment by jimoguilai** [comment]
> @jimoguilai 修改react_app/Basic.js为Basic.jsx后缀

不是，还没到这一步，就vite.config.ts 里面配置plugins的时候，运行npm run dev就报错了。。

**Comment by jimoguilai** [comment]
@zhangHongEn 不是，还没到这一步，就vite.config.ts里配置了`plugins: [
			veauryVitePlugins({
				type: 'vue'
			}),
			vueSetupExtend(),
			viteCompression(),
			JSON.parse(env.VITE_OPEN_CDN) ? buildConfig.cdn() : null,`
后，运行项目 npm run dev就报错了

**Comment by zhangHongEn** [comment]
@jimoguilai 去掉veauryVitePlugins和basic.js仍然报错, 先配置好基础vue环境
