### ISSUE TITLE
直接把Basic Demo 拷贝到项目里面跑步起来啊。。

### ISSUE THREAD

**Issue by hyzx86** [devilwjp/veaury#9]
换了异步导入方式也是不行~~ 

![image](https://user-images.githubusercontent.com/15613121/168980469-7bef4d0f-7724-4fdf-804d-1a1a90c4881a.png)

**Comment by hyzx86** [comment]
react 18. 因为 amis 里面用的是18
```
"react": "^18.0.0",
 "react-dom": "^18.0.0",
```

**Comment by devilwjp** [comment]
@hyzx86 
在vue项目中开发react组件，并且需要手写react的jsx，那么需要在babel中添加veaury的ReactPreset

**Comment by devilwjp** [comment]
@hyzx86 
如果你是vite项目，按如下配置  
```js
// vite.config.js
import vue from '@vitejs/plugin-vue'
import react from '@vitejs/plugin-react'

export default {
  plugins: [
    vue({
      exclude: [/[/\\]react_app[\\/$]+/]
    }),
    react({
      include: [/[/\\]react_app[\\/$]+/]
    })
  ]
}
```

**Comment by hyzx86** [comment]
好的，我试试看，我昨天把源码翻出来调试。。都找不到原因。
打印的日志看起来很靠谱。。出来的东西就很离谱
 
![image](https://user-images.githubusercontent.com/15613121/169188509-0fab6c8f-c8eb-4670-9b33-b73d502ae234.png)

**Comment by devilwjp** [comment]
@hyzx86 
有问题随时提就行
